<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EthnicSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $ethnics = [
            ["id" => "1", "name" => "SUKU ACEH"],
            ["id" => "2", "name" => "SUKU ALAS"],
            ["id" => "3", "name" => "SUKU ALOR"],
            ["id" => "4", "name" => "SUKU AMBON"],
            ["id" => "5", "name" => "SUKU AMPANA"],
            ["id" => "6", "name" => "SUKU ANAK DALAM"],
            ["id" => "7", "name" => "SUKU ANEUK JAMEE"],
            ["id" => "8", "name" => "SUKU ARAB-INDONESIA"],
            ["id" => "9", "name" => "SUKU ARU"],
            ["id" => "10", "name" => "SUKU ASMAT"],
            ["id" => "11", "name" => "SUKU BARE\'E"],
            ["id" => "12", "name" => "SUKU BALI"],
            ["id" => "13", "name" => "SUKU BALANTAK"],
            ["id" => "14", "name" => "SUKU BANGGAI"],
            ["id" => "15", "name" => "SUKU BANTEN"],
            ["id" => "16", "name" => "SUKU BADUI"],
            ["id" => "17", "name" => "SUKU BANJAU"],
            ["id" => "18", "name" => "SUKU BANJAR"],
            ["id" => "19", "name" => "SUKU BATAK"],
            ["id" => "20", "name" => "SUKU KARO"],
            ["id" => "21", "name" => "SUKU MANDAILING"],
            ["id" => "22", "name" => "SUKU ANGKOLA"],
            ["id" => "23", "name" => "SUKU TOBA"],
            ["id" => "24", "name" => "SUKU PAKPAK"],
            ["id" => "25", "name" => "SUKU SIMALUNGUN"],
            ["id" => "26", "name" => "SUKU BATIN"],
            ["id" => "27", "name" => "SUKU BAWEAN"],
            ["id" => "28", "name" => "SUKU BENTONG"],
            ["id" => "29", "name" => "SUKU BERAU"],
            ["id" => "30", "name" => "SUKU BETAWI"],
            ["id" => "31", "name" => "SUKU BIMA"],
            ["id" => "32", "name" => "SUKU BOTI"],
            ["id" => "33", "name" => "SUKU BOLANG MONGONDOW"],
            ["id" => "34", "name" => "SUKU BUGIS"],
            ["id" => "35", "name" => "SUKU BUGIS PAGATAN"],
            ["id" => "36", "name" => "SUKU BUNGKU"],
            ["id" => "37", "name" => "SUKU BURU"],
            ["id" => "38", "name" => "SUKU BUOL"],
            ["id" => "39", "name" => "SUKU BULUNGAN"],
            ["id" => "40", "name" => "SUKU BUTON"],
            ["id" => "41", "name" => "SUKU BONAI"],
            ["id" => "42", "name" => "SUKU CIREBON"],
            ["id" => "43", "name" => "SUKU DAMAL"],
            ["id" => "44", "name" => "SUKU DAMPELES"],
            ["id" => "45", "name" => "SUKU DANI"],
            ["id" => "46", "name" => "SUKU DAIRI"],
            ["id" => "47", "name" => "SUKU DAYA"],
            ["id" => "48", "name" => "SUKU DAYAK"],
            ["id" => "49", "name" => "SUKU DAYAK AHE"],
            ["id" => "50", "name" => "SUKU DAYAK BAJARE"],
            ["id" => "51", "name" => "SUKU DAYAK DAMEA"],
            ["id" => "52", "name" => "SUKU DAYAK BANYADU"],
            ["id" => "53", "name" => "SUKU BAKATI"],
            ["id" => "54", "name" => "SUKU PUNAN"],
            ["id" => "55", "name" => "SUKU KANAYATN"],
            ["id" => "56", "name" => "SUKU DAYAK KRIO"],
            ["id" => "57", "name" => "SUKU DAYAK SUNGAI LAUR"],
            ["id" => "58", "name" => "SUKU DAYAK SIMPANGH"],
            ["id" => "59", "name" => "SUKU IBAN"],
            ["id" => "60", "name" => "SUKU DOMPU"],
            ["id" => "61", "name" => "SUKU DONGGO"],
            ["id" => "62", "name" => "SUKU DONGGALA"],
            ["id" => "63", "name" => "SUKU DONDO"],
            ["id" => "64", "name" => "SUKU DURI"],
            ["id" => "65", "name" => "SUKU EROPA-INDONESIA"],
            ["id" => "66", "name" => "SUKU LAMAHOLOT"],
            ["id" => "67", "name" => "SUKU WANDAN"],
            ["id" => "68", "name" => "SUKU KALIHA"],
            ["id" => "69", "name" => "SUKU SERANG GORANG"],
            ["id" => "70", "name" => "SUKU LAMAROBAK"],
            ["id" => "71", "name" => "SUKU ATANUHAN"],
            ["id" => "72", "name" => "SUKU WOTAN"],
            ["id" => "73", "name" => "SUKU KAPITAN BELEN"],
            ["id" => "74", "name" => "SUKU GAYO "],
            ["id" => "75", "name" => "SUKU GORONTALO"],
            ["id" => "76", "name" => "SUKU GUMAI"],
            ["id" => "77", "name" => "SUKU INDIA-INDONESIA"],
            ["id" => "78", "name" => "SUKU JAWA"],
            ["id" => "79", "name" => "SUKU JAMBI"],
            ["id" => "80", "name" => "SUKU KEI"],
            ["id" => "81", "name" => "SUKU KAILI"],
            ["id" => "82", "name" => "SUKU KAUR"],
            ["id" => "83", "name" => "SUKU KAYU AGUNG"],
            ["id" => "84", "name" => "SUKU KERINCI"],
            ["id" => "85", "name" => "SUKU KOMERING"],
            ["id" => "86", "name" => "SUKU KONJO PEGUNUNGAN"],
            ["id" => "87", "name" => "SUKU KONJO PESISIR"],
            ["id" => "88", "name" => "SUKU KOTO"],
            ["id" => "89", "name" => "SUKU KUBU"],
            ["id" => "90", "name" => "SUKU KULAWI"],
            ["id" => "91", "name" => "SUKU KUTAI"],
            ["id" => "92", "name" => "SUKU KLUET"],
            ["id" => "93", "name" => "SUKU KRUI"],
            ["id" => "94", "name" => "SUKU LAUT"],
            ["id" => "95", "name" => "SUKU LAMPUNG"],
            ["id" => "96", "name" => "SUKU LEMATANG"],
            ["id" => "97", "name" => "SUKU LEMBAK"],
            ["id" => "98", "name" => "SUKU LINTANG"],
            ["id" => "99", "name" => "SUKU LOM"],
            ["id" => "100", "name" => "SUKU LORE"],
            ["id" => "101", "name" => "SUKU LUBU"],
            ["id" => "102", "name" => "SUKU MORONENE"],
            ["id" => "103", "name" => "SUKU MADURA"],
            ["id" => "104", "name" => "SUKU MAKASSAR"],
            ["id" => "105", "name" => "SUKU MAMASA"],
            ["id" => "106", "name" => "SUKU MANDAR"],
            ["id" => "107", "name" => "SUKU MELAYU"],
            ["id" => "108", "name" => "SUKU MENTAWAI"],
            ["id" => "109", "name" => "SUKU MINAHASA"],
            ["id" => "110", "name" => "SUKU MINANGKABAU"],
            ["id" => "111", "name" => "SUKU MONGONDOW"],
            ["id" => "112", "name" => "SUKU MORI"],
            ["id" => "113", "name" => "SUKU MUKO-MUKO"],
            ["id" => "114", "name" => "SUKU MUNA"],
            ["id" => "115", "name" => "SUKU MUYU"],
            ["id" => "116", "name" => "SUKU MEKONGGA"],
            ["id" => "117", "name" => "SUKU NIAS"],
            ["id" => "118", "name" => "SUKU NGADA"],
            ["id" => "119", "name" => "SUKU OSING"],
            ["id" => "120", "name" => "SUKU OGAN"],
            ["id" => "121", "name" => "SUKU OCU"],
            ["id" => "122", "name" => "SUKU PADOE"],
            ["id" => "123", "name" => "SUKU BIAK"],
            ["id" => "124", "name" => "SUKU DANI"],
            ["id" => "125", "name" => "SUKU EKAGI"],
            ["id" => "126", "name" => "SUKU AMUNGME"],
            ["id" => "127", "name" => "SUKU BAUZI"],
            ["id" => "128", "name" => "SUKU ARFAK"],
            ["id" => "129", "name" => "SUKU KAMORO"],
            ["id" => "130", "name" => "SUKU PALEMBANG"],
            ["id" => "131", "name" => "SUKU PAMONA"],
            ["id" => "132", "name" => "SUKU BASEMAH"],
            ["id" => "133", "name" => "SUKU PESISI"],
            ["id" => "134", "name" => "SUKU PASIR"],
            ["id" => "135", "name" => "SUKU PUBIAN"],
            ["id" => "136", "name" => "SUKU PATTAE"],
            ["id" => "137", "name" => "SUKU RAWA"],
            ["id" => "138", "name" => "SUKU REJANG"],
            ["id" => "139", "name" => "SUKU ROTE"],
            ["id" => "140", "name" => "SUKU RONGGA"],
            ["id" => "141", "name" => "SUKU SALUAN"],
            ["id" => "142", "name" => "SUKU SAMBAS"],
            ["id" => "143", "name" => "SUKU SAMIN"],
            ["id" => "144", "name" => "SUKU SANGIR"],
            ["id" => "145", "name" => "SUKU SASAK"],
            ["id" => "146", "name" => "SUKU SEKAK BANGKA"],
            ["id" => "147", "name" => "SUKU SEKAYU"],
            ["id" => "148", "name" => "SUKU SEMENDO"],
            ["id" => "149", "name" => "SUKU SERAWAI"],
            ["id" => "150", "name" => "SUKU SIMEULUE"],
            ["id" => "151", "name" => "SUKU SIGULAI"],
            ["id" => "152", "name" => "SUKU SUMBAWA"],
            ["id" => "153", "name" => "SUKU SUMBA"],
            ["id" => "154", "name" => "SUKU SUNDA"],
            ["id" => "155", "name" => "SUKU SUNGKAI"],
            ["id" => "156", "name" => "SUKU TALAUD"],
            ["id" => "157", "name" => "SUKU TALANG MAMAK"],
            ["id" => "158", "name" => "SUKU TAMIANG"],
            ["id" => "159", "name" => "SUKU TENGGER"],
            ["id" => "160", "name" => "SUKU TERNATE"],
            ["id" => "161", "name" => "SUKU TIDORE"],
            ["id" => "162", "name" => "SUKU TIDUNG"],
            ["id" => "163", "name" => "SUKU TIMOR"],
            ["id" => "164", "name" => "SUKU TIONGHOA"],
            ["id" => "165", "name" => "SUKU TOJO"],
            ["id" => "166", "name" => "SUKU TORAJA"],
            ["id" => "167", "name" => "SUKU TOLAKI"],
            ["id" => "168", "name" => "SUKU TOLI-TOLI"],
            ["id" => "169", "name" => "SUKU TOMINI"],
            ["id" => "170", "name" => "SUKU UNA-UNA"],
            ["id" => "171", "name" => "SUKU WOLIO"],
            ["id" => "177", "name" => "TIDAK DIKETAHUI"],
            ["id" => "178", "name" => "SABU"],
            ["id" => "179", "name" => "SUKU FAKFAK"],
            ["id" => "180", "name" => "SUKU SARMI"],
            ["id" => "181", "name" => "SUKU PAPUA"],
            ["id" => "182", "name" => "SUKU MELANESIA"],
        ];

        DB::beginTransaction();
        try{
            foreach ($ethnics as $data){
                DB::table('suku')->insert([
                    'id' => intval($data['id']),
                    'name' => $data['name'],   
                ]);
            }
            DB::commit();
        }catch (\Exception $e){
            DB::rollBack();
            throw $e;
        }
    }
}
