<?php

namespace Database\Seeders\Geography;

use Illuminate\Database\Seeder;

use App\Models\Geography\Country;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $country = [
            [
                "Id_Negara" => "1",
                "Kode_Negara" => "AF",
                "Nama_Negara" => "AFGHANISTAN",
                "Kode_Negara_Alpaha_3" => "AFG",
            ],
            [
                "Id_Negara" => "2",
                "Kode_Negara" => "AL",
                "Nama_Negara" => "ALBANIA",
                "Kode_Negara_Alpaha_3" => "ALB",
            ],
            [
                "Id_Negara" => "3",
                "Kode_Negara" => "DZ",
                "Nama_Negara" => "ALGERIA",
                "Kode_Negara_Alpaha_3" => "DZA",
            ],
            [
                "Id_Negara" => "4",
                "Kode_Negara" => "AS",
                "Nama_Negara" => "AMERICAN SAMOA",
                "Kode_Negara_Alpaha_3" => "ASM",
            ],
            [
                "Id_Negara" => "5",
                "Kode_Negara" => "AD",
                "Nama_Negara" => "ANDORRA",
                "Kode_Negara_Alpaha_3" => "AND",
            ],
            [
                "Id_Negara" => "6",
                "Kode_Negara" => "AO",
                "Nama_Negara" => "ANGOLA",
                "Kode_Negara_Alpaha_3" => "AGO",
            ],
            [
                "Id_Negara" => "7",
                "Kode_Negara" => "AI",
                "Nama_Negara" => "ANGUILLA",
                "Kode_Negara_Alpaha_3" => "AIA",
            ],
            [
                "Id_Negara" => "8",
                "Kode_Negara" => "AQ",
                "Nama_Negara" => "ANTARCTICA",
                "Kode_Negara_Alpaha_3" => "ATA",
            ],
            [
                "Id_Negara" => "9",
                "Kode_Negara" => "AG",
                "Nama_Negara" => "ANTIGUA AND BARBUDA",
                "Kode_Negara_Alpaha_3" => "ATG",
            ],
            [
                "Id_Negara" => "10",
                "Kode_Negara" => "AR",
                "Nama_Negara" => "ARGENTINA",
                "Kode_Negara_Alpaha_3" => "ARG",
            ],
            [
                "Id_Negara" => "11",
                "Kode_Negara" => "AM",
                "Nama_Negara" => "ARMENIA",
                "Kode_Negara_Alpaha_3" => "ARM",
            ],
            [
                "Id_Negara" => "12",
                "Kode_Negara" => "AW",
                "Nama_Negara" => "ARUBA",
                "Kode_Negara_Alpaha_3" => "ABW",
            ],
            [
                "Id_Negara" => "13",
                "Kode_Negara" => "AU",
                "Nama_Negara" => "AUSTRALIA",
                "Kode_Negara_Alpaha_3" => "AUS",
            ],
            [
                "Id_Negara" => "14",
                "Kode_Negara" => "AT",
                "Nama_Negara" => "AUSTRIA",
                "Kode_Negara_Alpaha_3" => "AUT",
            ],
            [
                "Id_Negara" => "15",
                "Kode_Negara" => "AZ",
                "Nama_Negara" => "AZERBAIJAN",
                "Kode_Negara_Alpaha_3" => "AZE",
            ],
            [
                "Id_Negara" => "16",
                "Kode_Negara" => "BS",
                "Nama_Negara" => "BAHAMAS",
                "Kode_Negara_Alpaha_3" => "BHS",
            ],
            [
                "Id_Negara" => "17",
                "Kode_Negara" => "BH",
                "Nama_Negara" => "BAHRAIN",
                "Kode_Negara_Alpaha_3" => "BHR",
            ],
            [
                "Id_Negara" => "18",
                "Kode_Negara" => "BD",
                "Nama_Negara" => "BANGLADESH",
                "Kode_Negara_Alpaha_3" => "BGD",
            ],
            [
                "Id_Negara" => "19",
                "Kode_Negara" => "BB",
                "Nama_Negara" => "BARBADOS",
                "Kode_Negara_Alpaha_3" => "BRB",
            ],
            [
                "Id_Negara" => "20",
                "Kode_Negara" => "BY",
                "Nama_Negara" => "BELARUS",
                "Kode_Negara_Alpaha_3" => "BLR",
            ],
            [
                "Id_Negara" => "21",
                "Kode_Negara" => "BE",
                "Nama_Negara" => "BELGIUM",
                "Kode_Negara_Alpaha_3" => "BEL",
            ],
            [
                "Id_Negara" => "22",
                "Kode_Negara" => "BZ",
                "Nama_Negara" => "BELIZE",
                "Kode_Negara_Alpaha_3" => "BLZ",
            ],
            [
                "Id_Negara" => "23",
                "Kode_Negara" => "BJ",
                "Nama_Negara" => "BENIN",
                "Kode_Negara_Alpaha_3" => "BEN",
            ],
            [
                "Id_Negara" => "24",
                "Kode_Negara" => "BM",
                "Nama_Negara" => "BERMUDA",
                "Kode_Negara_Alpaha_3" => "BMU",
            ],
            [
                "Id_Negara" => "25",
                "Kode_Negara" => "BT",
                "Nama_Negara" => "BHUTAN",
                "Kode_Negara_Alpaha_3" => "BTN",
            ],
            [
                "Id_Negara" => "26",
                "Kode_Negara" => "BO",
                "Nama_Negara" => "BOLIVIA",
                "Kode_Negara_Alpaha_3" => "BOL",
            ],
            [
                "Id_Negara" => "27",
                "Kode_Negara" => "BA",
                "Nama_Negara" => "BOSNIA AND HERZEGOVINA",
                "Kode_Negara_Alpaha_3" => "BIH",
            ],
            [
                "Id_Negara" => "28",
                "Kode_Negara" => "BW",
                "Nama_Negara" => "BOTSWANA",
                "Kode_Negara_Alpaha_3" => "BWA",
            ],
            [
                "Id_Negara" => "29",
                "Kode_Negara" => "BV",
                "Nama_Negara" => "BOUVET ISLAND",
                "Kode_Negara_Alpaha_3" => "BVT",
            ],
            [
                "Id_Negara" => "30",
                "Kode_Negara" => "BR",
                "Nama_Negara" => "BRAZIL",
                "Kode_Negara_Alpaha_3" => "BRA",
            ],
            [
                "Id_Negara" => "31",
                "Kode_Negara" => "IO",
                "Nama_Negara" => "BRITISH INDIAN OCEAN TERRITORY",
                "Kode_Negara_Alpaha_3" => "IOT",
            ],
            [
                "Id_Negara" => "32",
                "Kode_Negara" => "BN",
                "Nama_Negara" => "BRUNEI DARUSSALAM",
                "Kode_Negara_Alpaha_3" => "BRN",
            ],
            [
                "Id_Negara" => "33",
                "Kode_Negara" => "BG",
                "Nama_Negara" => "BULGARIA",
                "Kode_Negara_Alpaha_3" => "BGR",
            ],
            [
                "Id_Negara" => "34",
                "Kode_Negara" => "BF",
                "Nama_Negara" => "BURKINA FASO",
                "Kode_Negara_Alpaha_3" => "BFA",
            ],
            [
                "Id_Negara" => "35",
                "Kode_Negara" => "BI",
                "Nama_Negara" => "BURUNDI",
                "Kode_Negara_Alpaha_3" => "BDI",
            ],
            [
                "Id_Negara" => "36",
                "Kode_Negara" => "KH",
                "Nama_Negara" => "CAMBODIA",
                "Kode_Negara_Alpaha_3" => "KHM",
            ],
            [
                "Id_Negara" => "37",
                "Kode_Negara" => "CM",
                "Nama_Negara" => "CAMEROON",
                "Kode_Negara_Alpaha_3" => "CMR",
            ],
            [
                "Id_Negara" => "38",
                "Kode_Negara" => "CA",
                "Nama_Negara" => "CANADA",
                "Kode_Negara_Alpaha_3" => "CAN",
            ],
            [
                "Id_Negara" => "39",
                "Kode_Negara" => "CV",
                "Nama_Negara" => "CAPE VERDE",
                "Kode_Negara_Alpaha_3" => "CPV",
            ],
            [
                "Id_Negara" => "40",
                "Kode_Negara" => "KY",
                "Nama_Negara" => "CAYMAN ISLANDS",
                "Kode_Negara_Alpaha_3" => "CYM",
            ],
            [
                "Id_Negara" => "41",
                "Kode_Negara" => "CF",
                "Nama_Negara" => "CENTRAL AFRICAN REPUBLIC",
                "Kode_Negara_Alpaha_3" => "CAF",
            ],
            [
                "Id_Negara" => "42",
                "Kode_Negara" => "TD",
                "Nama_Negara" => "CHAD",
                "Kode_Negara_Alpaha_3" => "TCD",
            ],
            [
                "Id_Negara" => "43",
                "Kode_Negara" => "CL",
                "Nama_Negara" => "CHILE",
                "Kode_Negara_Alpaha_3" => "CHL",
            ],
            [
                "Id_Negara" => "44",
                "Kode_Negara" => "CN",
                "Nama_Negara" => "CHINA",
                "Kode_Negara_Alpaha_3" => "CHN",
            ],
            [
                "Id_Negara" => "45",
                "Kode_Negara" => "CX",
                "Nama_Negara" => "CHRISTMAS ISLAND",
                "Kode_Negara_Alpaha_3" => "CXR",
            ],
            [
                "Id_Negara" => "46",
                "Kode_Negara" => "CC",
                "Nama_Negara" => "COCOS (KEELING) ISLANDS",
                "Kode_Negara_Alpaha_3" => "CCK",
            ],
            [
                "Id_Negara" => "47",
                "Kode_Negara" => "CO",
                "Nama_Negara" => "COLOMBIA",
                "Kode_Negara_Alpaha_3" => "COL",
            ],
            [
                "Id_Negara" => "48",
                "Kode_Negara" => "KM",
                "Nama_Negara" => "COMOROS",
                "Kode_Negara_Alpaha_3" => "COM",
            ],
            [
                "Id_Negara" => "49",
                "Kode_Negara" => "CG",
                "Nama_Negara" => "CONGO",
                "Kode_Negara_Alpaha_3" => "COG",
            ],
            [
                "Id_Negara" => "50",
                "Kode_Negara" => "CK",
                "Nama_Negara" => "COOK ISLANDS",
                "Kode_Negara_Alpaha_3" => "COK",
            ],
            [
                "Id_Negara" => "51",
                "Kode_Negara" => "CR",
                "Nama_Negara" => "COSTA RICA",
                "Kode_Negara_Alpaha_3" => "CRI",
            ],
            [
                "Id_Negara" => "52",
                "Kode_Negara" => "HR",
                "Nama_Negara" => "CROATIA (HRVATSKA)",
                "Kode_Negara_Alpaha_3" => "HRV",
            ],
            [
                "Id_Negara" => "53",
                "Kode_Negara" => "CU",
                "Nama_Negara" => "CUBA",
                "Kode_Negara_Alpaha_3" => "CUB",
            ],
            [
                "Id_Negara" => "54",
                "Kode_Negara" => "CY",
                "Nama_Negara" => "CYPRUS",
                "Kode_Negara_Alpaha_3" => "CYP",
            ],
            [
                "Id_Negara" => "55",
                "Kode_Negara" => "CZ",
                "Nama_Negara" => "CZECH REPUBLIC",
                "Kode_Negara_Alpaha_3" => "CZE",
            ],
            [
                "Id_Negara" => "56",
                "Kode_Negara" => "DK",
                "Nama_Negara" => "DENMARK",
                "Kode_Negara_Alpaha_3" => "DNK",
            ],
            [
                "Id_Negara" => "57",
                "Kode_Negara" => "DJ",
                "Nama_Negara" => "DJIBOUTI",
                "Kode_Negara_Alpaha_3" => "DJI",
            ],
            [
                "Id_Negara" => "58",
                "Kode_Negara" => "DM",
                "Nama_Negara" => "DOMINICA",
                "Kode_Negara_Alpaha_3" => "DMA",
            ],
            [
                "Id_Negara" => "59",
                "Kode_Negara" => "DO",
                "Nama_Negara" => "DOMINICAN REPUBLIC",
                "Kode_Negara_Alpaha_3" => "DOM",
            ],
            [
                "Id_Negara" => "60",
                "Kode_Negara" => "TL",
                "Nama_Negara" => "EAST TIMOR",
                "Kode_Negara_Alpaha_3" => "TLS",
            ],
            [
                "Id_Negara" => "61",
                "Kode_Negara" => "EC",
                "Nama_Negara" => "ECUADOR",
                "Kode_Negara_Alpaha_3" => "ECU",
            ],
            [
                "Id_Negara" => "62",
                "Kode_Negara" => "EG",
                "Nama_Negara" => "EGYPT",
                "Kode_Negara_Alpaha_3" => "EGY",
            ],
            [
                "Id_Negara" => "63",
                "Kode_Negara" => "SV",
                "Nama_Negara" => "EL SALVADOR",
                "Kode_Negara_Alpaha_3" => "SLV",
            ],
            [
                "Id_Negara" => "64",
                "Kode_Negara" => "GQ",
                "Nama_Negara" => "EQUATORIAL GUINEA",
                "Kode_Negara_Alpaha_3" => "GNQ",
            ],
            [
                "Id_Negara" => "65",
                "Kode_Negara" => "ER",
                "Nama_Negara" => "ERITREA",
                "Kode_Negara_Alpaha_3" => "ERI",
            ],
            [
                "Id_Negara" => "66",
                "Kode_Negara" => "EE",
                "Nama_Negara" => "ESTONIA",
                "Kode_Negara_Alpaha_3" => "EST",
            ],
            [
                "Id_Negara" => "67",
                "Kode_Negara" => "ET",
                "Nama_Negara" => "ETHIOPIA",
                "Kode_Negara_Alpaha_3" => "ETH",
            ],
            [
                "Id_Negara" => "68",
                "Kode_Negara" => "FK",
                "Nama_Negara" => "FALKLAND ISLANDS (MALVINAS)",
                "Kode_Negara_Alpaha_3" => "FLK",
            ],
            [
                "Id_Negara" => "69",
                "Kode_Negara" => "FO",
                "Nama_Negara" => "FAROE ISLANDS",
                "Kode_Negara_Alpaha_3" => "FRO",
            ],
            [
                "Id_Negara" => "70",
                "Kode_Negara" => "FJ",
                "Nama_Negara" => "FIJI",
                "Kode_Negara_Alpaha_3" => "FJI",
            ],
            [
                "Id_Negara" => "71",
                "Kode_Negara" => "FI",
                "Nama_Negara" => "FINLAND",
                "Kode_Negara_Alpaha_3" => "FIN",
            ],
            [
                "Id_Negara" => "72",
                "Kode_Negara" => "FR",
                "Nama_Negara" => "FRANCE",
                "Kode_Negara_Alpaha_3" => "FRA",
            ],
            [
                "Id_Negara" => "73",
                "Kode_Negara" => "FX",
                "Nama_Negara" => "FRANCE, METROPOLITAN",
                "Kode_Negara_Alpaha_3" => "FXX",
            ],
            [
                "Id_Negara" => "74",
                "Kode_Negara" => "GF",
                "Nama_Negara" => "FRENCH GUIANA",
                "Kode_Negara_Alpaha_3" => "GUF",
            ],
            [
                "Id_Negara" => "75",
                "Kode_Negara" => "PF",
                "Nama_Negara" => "FRENCH POLYNESIA",
                "Kode_Negara_Alpaha_3" => "PYF",
            ],
            [
                "Id_Negara" => "76",
                "Kode_Negara" => "TF",
                "Nama_Negara" => "FRENCH SOUTHERN TERRITORIES",
                "Kode_Negara_Alpaha_3" => "ATF",
            ],
            [
                "Id_Negara" => "77",
                "Kode_Negara" => "GA",
                "Nama_Negara" => "GABON",
                "Kode_Negara_Alpaha_3" => "GAB",
            ],
            [
                "Id_Negara" => "78",
                "Kode_Negara" => "GM",
                "Nama_Negara" => "GAMBIA",
                "Kode_Negara_Alpaha_3" => "GMB",
            ],
            [
                "Id_Negara" => "79",
                "Kode_Negara" => "GE",
                "Nama_Negara" => "GEORGIA",
                "Kode_Negara_Alpaha_3" => "GEO",
            ],
            [
                "Id_Negara" => "80",
                "Kode_Negara" => "DE",
                "Nama_Negara" => "GERMANY",
                "Kode_Negara_Alpaha_3" => "DEU",
            ],
            [
                "Id_Negara" => "81",
                "Kode_Negara" => "GH",
                "Nama_Negara" => "GHANA",
                "Kode_Negara_Alpaha_3" => "GHA",
            ],
            [
                "Id_Negara" => "82",
                "Kode_Negara" => "GI",
                "Nama_Negara" => "GIBRALTAR",
                "Kode_Negara_Alpaha_3" => "GIB",
            ],
            [
                "Id_Negara" => "83",
                "Kode_Negara" => "GG",
                "Nama_Negara" => "GUERNSEY",
                "Kode_Negara_Alpaha_3" => "GGY",
            ],
            [
                "Id_Negara" => "84",
                "Kode_Negara" => "GR",
                "Nama_Negara" => "GREECE",
                "Kode_Negara_Alpaha_3" => "GRC",
            ],
            [
                "Id_Negara" => "85",
                "Kode_Negara" => "GL",
                "Nama_Negara" => "GREENLAND",
                "Kode_Negara_Alpaha_3" => "GRL",
            ],
            [
                "Id_Negara" => "86",
                "Kode_Negara" => "GD",
                "Nama_Negara" => "GRENADA",
                "Kode_Negara_Alpaha_3" => "GRD",
            ],
            [
                "Id_Negara" => "87",
                "Kode_Negara" => "GP",
                "Nama_Negara" => "GUADELOUPE",
                "Kode_Negara_Alpaha_3" => "GLP",
            ],
            [
                "Id_Negara" => "88",
                "Kode_Negara" => "GU",
                "Nama_Negara" => "GUAM",
                "Kode_Negara_Alpaha_3" => "GUM",
            ],
            [
                "Id_Negara" => "89",
                "Kode_Negara" => "GT",
                "Nama_Negara" => "GUATEMALA",
                "Kode_Negara_Alpaha_3" => "GTM",
            ],
            [
                "Id_Negara" => "90",
                "Kode_Negara" => "GN",
                "Nama_Negara" => "GUINEA",
                "Kode_Negara_Alpaha_3" => "GIN",
            ],
            [
                "Id_Negara" => "91",
                "Kode_Negara" => "GW",
                "Nama_Negara" => "GUINEA-BISSAU",
                "Kode_Negara_Alpaha_3" => "GNB",
            ],
            [
                "Id_Negara" => "92",
                "Kode_Negara" => "GY",
                "Nama_Negara" => "GUYANA",
                "Kode_Negara_Alpaha_3" => "GUY",
            ],
            [
                "Id_Negara" => "93",
                "Kode_Negara" => "HT",
                "Nama_Negara" => "HAITI",
                "Kode_Negara_Alpaha_3" => "HTI",
            ],
            [
                "Id_Negara" => "94",
                "Kode_Negara" => "HM",
                "Nama_Negara" => "HEARD AND MC DONALD ISLANDS",
                "Kode_Negara_Alpaha_3" => "HMD",
            ],
            [
                "Id_Negara" => "95",
                "Kode_Negara" => "HN",
                "Nama_Negara" => "HONDURAS",
                "Kode_Negara_Alpaha_3" => "HND",
            ],
            [
                "Id_Negara" => "96",
                "Kode_Negara" => "HK",
                "Nama_Negara" => "HONG KONG",
                "Kode_Negara_Alpaha_3" => "HKG",
            ],
            [
                "Id_Negara" => "97",
                "Kode_Negara" => "HU",
                "Nama_Negara" => "HUNGARY",
                "Kode_Negara_Alpaha_3" => "HUN",
            ],
            [
                "Id_Negara" => "98",
                "Kode_Negara" => "IS",
                "Nama_Negara" => "ICELAND",
                "Kode_Negara_Alpaha_3" => "ISL",
            ],
            [
                "Id_Negara" => "99",
                "Kode_Negara" => "IN",
                "Nama_Negara" => "INDIA",
                "Kode_Negara_Alpaha_3" => "IND",
            ],
            [
                "Id_Negara" => "100",
                "Kode_Negara" => "IM",
                "Nama_Negara" => "ISLE OF MAN",
                "Kode_Negara_Alpaha_3" => "IMN",
            ],
            [
                "Id_Negara" => "101",
                "Kode_Negara" => "ID",
                "Nama_Negara" => "INDONESIA",
                "Kode_Negara_Alpaha_3" => "IDN",
            ],
            [
                "Id_Negara" => "102",
                "Kode_Negara" => "IR",
                "Nama_Negara" => "IRAN (ISLAMIC REPUBLIC OF)",
                "Kode_Negara_Alpaha_3" => "IRN",
            ],
            [
                "Id_Negara" => "103",
                "Kode_Negara" => "IQ",
                "Nama_Negara" => "IRAQ",
                "Kode_Negara_Alpaha_3" => "IRQ",
            ],
            [
                "Id_Negara" => "104",
                "Kode_Negara" => "IE",
                "Nama_Negara" => "IRELAND",
                "Kode_Negara_Alpaha_3" => "IRL",
            ],
            [
                "Id_Negara" => "105",
                "Kode_Negara" => "IL",
                "Nama_Negara" => "ISRAEL",
                "Kode_Negara_Alpaha_3" => "ISR",
            ],
            [
                "Id_Negara" => "106",
                "Kode_Negara" => "IT",
                "Nama_Negara" => "ITALY",
                "Kode_Negara_Alpaha_3" => "ITA",
            ],
            [
                "Id_Negara" => "107",
                "Kode_Negara" => "CI",
                "Nama_Negara" => "IVORY COAST",
                "Kode_Negara_Alpaha_3" => "CIV",
            ],
            [
                "Id_Negara" => "108",
                "Kode_Negara" => "JE",
                "Nama_Negara" => "JERSEY",
                "Kode_Negara_Alpaha_3" => "JEY",
            ],
            [
                "Id_Negara" => "109",
                "Kode_Negara" => "JM",
                "Nama_Negara" => "JAMAICA",
                "Kode_Negara_Alpaha_3" => "JAM",
            ],
            [
                "Id_Negara" => "110",
                "Kode_Negara" => "JP",
                "Nama_Negara" => "JAPAN",
                "Kode_Negara_Alpaha_3" => "JPN",
            ],
            [
                "Id_Negara" => "111",
                "Kode_Negara" => "JO",
                "Nama_Negara" => "JORDAN",
                "Kode_Negara_Alpaha_3" => "JOR",
            ],
            [
                "Id_Negara" => "112",
                "Kode_Negara" => "KZ",
                "Nama_Negara" => "KAZAKHSTAN",
                "Kode_Negara_Alpaha_3" => "KAZ",
            ],
            [
                "Id_Negara" => "113",
                "Kode_Negara" => "KE",
                "Nama_Negara" => "KENYA",
                "Kode_Negara_Alpaha_3" => "KEN",
            ],
            [
                "Id_Negara" => "114",
                "Kode_Negara" => "KI",
                "Nama_Negara" => "KIRIBATI",
                "Kode_Negara_Alpaha_3" => "KIR",
            ],
            [
                "Id_Negara" => "115",
                "Kode_Negara" => "KP",
                "Nama_Negara" => "KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF",
                "Kode_Negara_Alpaha_3" => "PRK",
            ],
            [
                "Id_Negara" => "116",
                "Kode_Negara" => "KR",
                "Nama_Negara" => "KOREA, REPUBLIC OF",
                "Kode_Negara_Alpaha_3" => "KOR",
            ],
            [
                "Id_Negara" => "117",
                "Kode_Negara" => "XK",
                "Nama_Negara" => "KOSOVO",
                "Kode_Negara_Alpaha_3" => "XKX",
            ],
            [
                "Id_Negara" => "118",
                "Kode_Negara" => "KW",
                "Nama_Negara" => "KUWAIT",
                "Kode_Negara_Alpaha_3" => "KWT",
            ],
            [
                "Id_Negara" => "119",
                "Kode_Negara" => "KG",
                "Nama_Negara" => "KYRGYZSTAN",
                "Kode_Negara_Alpaha_3" => "KGZ",
            ],
            [
                "Id_Negara" => "120",
                "Kode_Negara" => "LA",
                "Nama_Negara" => "LAO PEOPLE\'S DEMOCRATIC REPUBLIC",
                "Kode_Negara_Alpaha_3" => "LAO",
            ],
            [
                "Id_Negara" => "121",
                "Kode_Negara" => "LV",
                "Nama_Negara" => "LATVIA",
                "Kode_Negara_Alpaha_3" => "LVA",
            ],
            [
                "Id_Negara" => "122",
                "Kode_Negara" => "LB",
                "Nama_Negara" => "LEBANON",
                "Kode_Negara_Alpaha_3" => "LBN",
            ],
            [
                "Id_Negara" => "123",
                "Kode_Negara" => "LS",
                "Nama_Negara" => "LESOTHO",
                "Kode_Negara_Alpaha_3" => "LSO",
            ],
            [
                "Id_Negara" => "124",
                "Kode_Negara" => "LR",
                "Nama_Negara" => "LIBERIA",
                "Kode_Negara_Alpaha_3" => "LBR",
            ],
            [
                "Id_Negara" => "125",
                "Kode_Negara" => "LY",
                "Nama_Negara" => "LIBYAN ARAB JAMAHIRIYA",
                "Kode_Negara_Alpaha_3" => "LBY",
            ],
            [
                "Id_Negara" => "126",
                "Kode_Negara" => "LI",
                "Nama_Negara" => "LIECHTENSTEIN",
                "Kode_Negara_Alpaha_3" => "LIE",
            ],
            [
                "Id_Negara" => "127",
                "Kode_Negara" => "LT",
                "Nama_Negara" => "LITHUANIA",
                "Kode_Negara_Alpaha_3" => "LTU",
            ],
            [
                "Id_Negara" => "128",
                "Kode_Negara" => "LU",
                "Nama_Negara" => "LUXEMBOURG",
                "Kode_Negara_Alpaha_3" => "LUX",
            ],
            [
                "Id_Negara" => "129",
                "Kode_Negara" => "MO",
                "Nama_Negara" => "MACAU",
                "Kode_Negara_Alpaha_3" => "MAC",
            ],
            [
                "Id_Negara" => "130",
                "Kode_Negara" => "MK",
                "Nama_Negara" => "MACEDONIA",
                "Kode_Negara_Alpaha_3" => "MKD",
            ],
            [
                "Id_Negara" => "131",
                "Kode_Negara" => "MG",
                "Nama_Negara" => "MADAGASCAR",
                "Kode_Negara_Alpaha_3" => "MDG",
            ],
            [
                "Id_Negara" => "132",
                "Kode_Negara" => "MW",
                "Nama_Negara" => "MALAWI",
                "Kode_Negara_Alpaha_3" => "MWI",
            ],
            [
                "Id_Negara" => "133",
                "Kode_Negara" => "MY",
                "Nama_Negara" => "MALAYSIA",
                "Kode_Negara_Alpaha_3" => "MYS",
            ],
            [
                "Id_Negara" => "134",
                "Kode_Negara" => "MV",
                "Nama_Negara" => "MALDIVES",
                "Kode_Negara_Alpaha_3" => "MDV",
            ],
            [
                "Id_Negara" => "135",
                "Kode_Negara" => "ML",
                "Nama_Negara" => "MALI",
                "Kode_Negara_Alpaha_3" => "MLI",
            ],
            [
                "Id_Negara" => "136",
                "Kode_Negara" => "MT",
                "Nama_Negara" => "MALTA",
                "Kode_Negara_Alpaha_3" => "MLT",
            ],
            [
                "Id_Negara" => "137",
                "Kode_Negara" => "MH",
                "Nama_Negara" => "MARSHALL ISLANDS",
                "Kode_Negara_Alpaha_3" => "MHL",
            ],
            [
                "Id_Negara" => "138",
                "Kode_Negara" => "MQ",
                "Nama_Negara" => "MARTINIQUE",
                "Kode_Negara_Alpaha_3" => "MTQ",
            ],
            [
                "Id_Negara" => "139",
                "Kode_Negara" => "MR",
                "Nama_Negara" => "MAURITANIA",
                "Kode_Negara_Alpaha_3" => "MRT",
            ],
            [
                "Id_Negara" => "140",
                "Kode_Negara" => "MU",
                "Nama_Negara" => "MAURITIUS",
                "Kode_Negara_Alpaha_3" => "MUS",
            ],
            [
                "Id_Negara" => "141",
                "Kode_Negara" => "YT",
                "Nama_Negara" => "MAYOTTE",
                "Kode_Negara_Alpaha_3" => "MYT",
            ],
            [
                "Id_Negara" => "142",
                "Kode_Negara" => "MX",
                "Nama_Negara" => "MEXICO",
                "Kode_Negara_Alpaha_3" => "MEX",
            ],
            [
                "Id_Negara" => "143",
                "Kode_Negara" => "FM",
                "Nama_Negara" => "MICRONESIA, FEDERATED STATES OF",
                "Kode_Negara_Alpaha_3" => "FSM",
            ],
            [
                "Id_Negara" => "144",
                "Kode_Negara" => "MD",
                "Nama_Negara" => "MOLDOVA, REPUBLIC OF",
                "Kode_Negara_Alpaha_3" => "MDA",
            ],
            [
                "Id_Negara" => "145",
                "Kode_Negara" => "MC",
                "Nama_Negara" => "MONACO",
                "Kode_Negara_Alpaha_3" => "MCO",
            ],
            [
                "Id_Negara" => "146",
                "Kode_Negara" => "MN",
                "Nama_Negara" => "MONGOLIA",
                "Kode_Negara_Alpaha_3" => "MNG",
            ],
            [
                "Id_Negara" => "147",
                "Kode_Negara" => "ME",
                "Nama_Negara" => "MONTENEGRO",
                "Kode_Negara_Alpaha_3" => "MNE",
            ],
            [
                "Id_Negara" => "148",
                "Kode_Negara" => "MS",
                "Nama_Negara" => "MONTSERRAT",
                "Kode_Negara_Alpaha_3" => "MSR",
            ],
            [
                "Id_Negara" => "149",
                "Kode_Negara" => "MA",
                "Nama_Negara" => "MOROCCO",
                "Kode_Negara_Alpaha_3" => "MAR",
            ],
            [
                "Id_Negara" => "150",
                "Kode_Negara" => "MZ",
                "Nama_Negara" => "MOZAMBIQUE",
                "Kode_Negara_Alpaha_3" => "MOZ",
            ],
            [
                "Id_Negara" => "151",
                "Kode_Negara" => "MM",
                "Nama_Negara" => "MYANMAR",
                "Kode_Negara_Alpaha_3" => "MMR",
            ],
            [
                "Id_Negara" => "152",
                "Kode_Negara" => "NA",
                "Nama_Negara" => "NAMIBIA",
                "Kode_Negara_Alpaha_3" => "NAM",
            ],
            [
                "Id_Negara" => "153",
                "Kode_Negara" => "NR",
                "Nama_Negara" => "NAURU",
                "Kode_Negara_Alpaha_3" => "NRU",
            ],
            [
                "Id_Negara" => "154",
                "Kode_Negara" => "NP",
                "Nama_Negara" => "NEPAL",
                "Kode_Negara_Alpaha_3" => "NPL",
            ],
            [
                "Id_Negara" => "155",
                "Kode_Negara" => "NL",
                "Nama_Negara" => "NETHERLANDS",
                "Kode_Negara_Alpaha_3" => "NLD",
            ],
            [
                "Id_Negara" => "156",
                "Kode_Negara" => "AN",
                "Nama_Negara" => "NETHERLANDS ANTILLES",
                "Kode_Negara_Alpaha_3" => "ANT",
            ],
            [
                "Id_Negara" => "157",
                "Kode_Negara" => "NC",
                "Nama_Negara" => "NEW CALEDONIA",
                "Kode_Negara_Alpaha_3" => "NCL",
            ],
            [
                "Id_Negara" => "158",
                "Kode_Negara" => "NZ",
                "Nama_Negara" => "NEW ZEALAND",
                "Kode_Negara_Alpaha_3" => "NZL",
            ],
            [
                "Id_Negara" => "159",
                "Kode_Negara" => "NI",
                "Nama_Negara" => "NICARAGUA",
                "Kode_Negara_Alpaha_3" => "NIC",
            ],
            [
                "Id_Negara" => "160",
                "Kode_Negara" => "NE",
                "Nama_Negara" => "NIGER",
                "Kode_Negara_Alpaha_3" => "NER",
            ],
            [
                "Id_Negara" => "161",
                "Kode_Negara" => "NG",
                "Nama_Negara" => "NIGERIA",
                "Kode_Negara_Alpaha_3" => "NGA",
            ],
            [
                "Id_Negara" => "162",
                "Kode_Negara" => "NU",
                "Nama_Negara" => "NIUE",
                "Kode_Negara_Alpaha_3" => "NIU",
            ],
            [
                "Id_Negara" => "163",
                "Kode_Negara" => "NF",
                "Nama_Negara" => "NORFOLK ISLAND",
                "Kode_Negara_Alpaha_3" => "NFK",
            ],
            [
                "Id_Negara" => "164",
                "Kode_Negara" => "MP",
                "Nama_Negara" => "NORTHERN MARIANA ISLANDS",
                "Kode_Negara_Alpaha_3" => "MNP",
            ],
            [
                "Id_Negara" => "165",
                "Kode_Negara" => "NO",
                "Nama_Negara" => "NORWAY",
                "Kode_Negara_Alpaha_3" => "NOR",
            ],
            [
                "Id_Negara" => "166",
                "Kode_Negara" => "OM",
                "Nama_Negara" => "OMAN",
                "Kode_Negara_Alpaha_3" => "OMN",
            ],
            [
                "Id_Negara" => "167",
                "Kode_Negara" => "PK",
                "Nama_Negara" => "PAKISTAN",
                "Kode_Negara_Alpaha_3" => "PAK",
            ],
            [
                "Id_Negara" => "168",
                "Kode_Negara" => "PW",
                "Nama_Negara" => "PALAU",
                "Kode_Negara_Alpaha_3" => "PLW",
            ],
            [
                "Id_Negara" => "169",
                "Kode_Negara" => "PS",
                "Nama_Negara" => "PALESTINE",
                "Kode_Negara_Alpaha_3" => "PSE",
            ],
            [
                "Id_Negara" => "170",
                "Kode_Negara" => "PA",
                "Nama_Negara" => "PANAMA",
                "Kode_Negara_Alpaha_3" => "PAN",
            ],
            [
                "Id_Negara" => "171",
                "Kode_Negara" => "PG",
                "Nama_Negara" => "PAPUA NEW GUINEA",
                "Kode_Negara_Alpaha_3" => "PNG",
            ],
            [
                "Id_Negara" => "172",
                "Kode_Negara" => "PY",
                "Nama_Negara" => "PARAGUAY",
                "Kode_Negara_Alpaha_3" => "PRY",
            ],
            [
                "Id_Negara" => "173",
                "Kode_Negara" => "PE",
                "Nama_Negara" => "PERU",
                "Kode_Negara_Alpaha_3" => "PER",
            ],
            [
                "Id_Negara" => "174",
                "Kode_Negara" => "PH",
                "Nama_Negara" => "PHILIPPINES",
                "Kode_Negara_Alpaha_3" => "PHL",
            ],
            [
                "Id_Negara" => "175",
                "Kode_Negara" => "PN",
                "Nama_Negara" => "PITCAIRN",
                "Kode_Negara_Alpaha_3" => "PCN",
            ],
            [
                "Id_Negara" => "176",
                "Kode_Negara" => "PL",
                "Nama_Negara" => "POLAND",
                "Kode_Negara_Alpaha_3" => "POL",
            ],
            [
                "Id_Negara" => "177",
                "Kode_Negara" => "PT",
                "Nama_Negara" => "PORTUGAL",
                "Kode_Negara_Alpaha_3" => "PRT",
            ],
            [
                "Id_Negara" => "178",
                "Kode_Negara" => "PR",
                "Nama_Negara" => "PUERTO RICO",
                "Kode_Negara_Alpaha_3" => "PRI",
            ],
            [
                "Id_Negara" => "179",
                "Kode_Negara" => "QA",
                "Nama_Negara" => "QATAR",
                "Kode_Negara_Alpaha_3" => "QAT",
            ],
            [
                "Id_Negara" => "180",
                "Kode_Negara" => "RE",
                "Nama_Negara" => "REUNION",
                "Kode_Negara_Alpaha_3" => "REU",
            ],
            [
                "Id_Negara" => "181",
                "Kode_Negara" => "RO",
                "Nama_Negara" => "ROMANIA",
                "Kode_Negara_Alpaha_3" => "ROU",
            ],
            [
                "Id_Negara" => "182",
                "Kode_Negara" => "RU",
                "Nama_Negara" => "RUSSIAN FEDERATION",
                "Kode_Negara_Alpaha_3" => "RUS",
            ],
            [
                "Id_Negara" => "183",
                "Kode_Negara" => "RW",
                "Nama_Negara" => "RWANDA",
                "Kode_Negara_Alpaha_3" => "RWA",
            ],
            [
                "Id_Negara" => "184",
                "Kode_Negara" => "KN",
                "Nama_Negara" => "SAINT KITTS AND NEVIS",
                "Kode_Negara_Alpaha_3" => "KNA",
            ],
            [
                "Id_Negara" => "185",
                "Kode_Negara" => "LC",
                "Nama_Negara" => "SAINT LUCIA",
                "Kode_Negara_Alpaha_3" => "LCA",
            ],
            [
                "Id_Negara" => "186",
                "Kode_Negara" => "VC",
                "Nama_Negara" => "SAINT VINCENT AND THE GRENADINES",
                "Kode_Negara_Alpaha_3" => "VCT",
            ],
            [
                "Id_Negara" => "187",
                "Kode_Negara" => "WS",
                "Nama_Negara" => "SAMOA",
                "Kode_Negara_Alpaha_3" => "WSM",
            ],
            [
                "Id_Negara" => "188",
                "Kode_Negara" => "SM",
                "Nama_Negara" => "SAN MARINO",
                "Kode_Negara_Alpaha_3" => "SMR",
            ],
            [
                "Id_Negara" => "189",
                "Kode_Negara" => "ST",
                "Nama_Negara" => "SAO TOME AND PRINCIPE",
                "Kode_Negara_Alpaha_3" => "STP",
            ],
            [
                "Id_Negara" => "190",
                "Kode_Negara" => "SA",
                "Nama_Negara" => "SAUDI ARABIA",
                "Kode_Negara_Alpaha_3" => "SAU",
            ],
            [
                "Id_Negara" => "191",
                "Kode_Negara" => "SN",
                "Nama_Negara" => "SENEGAL",
                "Kode_Negara_Alpaha_3" => "SEN",
            ],
            [
                "Id_Negara" => "192",
                "Kode_Negara" => "RS",
                "Nama_Negara" => "SERBIA",
                "Kode_Negara_Alpaha_3" => "SRB",
            ],
            [
                "Id_Negara" => "193",
                "Kode_Negara" => "SC",
                "Nama_Negara" => "SEYCHELLES",
                "Kode_Negara_Alpaha_3" => "SYC",
            ],
            [
                "Id_Negara" => "194",
                "Kode_Negara" => "SL",
                "Nama_Negara" => "SIERRA LEONE",
                "Kode_Negara_Alpaha_3" => "SLE",
            ],
            [
                "Id_Negara" => "195",
                "Kode_Negara" => "SG",
                "Nama_Negara" => "SINGAPORE",
                "Kode_Negara_Alpaha_3" => "SGP",
            ],
            [
                "Id_Negara" => "196",
                "Kode_Negara" => "SK",
                "Nama_Negara" => "SLOVAKIA",
                "Kode_Negara_Alpaha_3" => "SVK",
            ],
            [
                "Id_Negara" => "197",
                "Kode_Negara" => "SI",
                "Nama_Negara" => "SLOVENIA",
                "Kode_Negara_Alpaha_3" => "SVN",
            ],
            [
                "Id_Negara" => "198",
                "Kode_Negara" => "SB",
                "Nama_Negara" => "SOLOMON ISLANDS",
                "Kode_Negara_Alpaha_3" => "SLB",
            ],
            [
                "Id_Negara" => "199",
                "Kode_Negara" => "SO",
                "Nama_Negara" => "SOMALIA",
                "Kode_Negara_Alpaha_3" => "SOM",
            ],
            [
                "Id_Negara" => "200",
                "Kode_Negara" => "ZA",
                "Nama_Negara" => "SOUTH AFRICA",
                "Kode_Negara_Alpaha_3" => "ZAF",
            ],
            [
                "Id_Negara" => "201",
                "Kode_Negara" => "GS",
                "Nama_Negara" => "SOUTH GEORGIA SOUTH SANDWICH ISLANDS",
                "Kode_Negara_Alpaha_3" => "SGS",
            ],
            [
                "Id_Negara" => "202",
                "Kode_Negara" => "ES",
                "Nama_Negara" => "SPAIN",
                "Kode_Negara_Alpaha_3" => "ESP",
            ],
            [
                "Id_Negara" => "203",
                "Kode_Negara" => "LK",
                "Nama_Negara" => "SRI LANKA",
                "Kode_Negara_Alpaha_3" => "LKA",
            ],
            [
                "Id_Negara" => "204",
                "Kode_Negara" => "SH",
                "Nama_Negara" => "ST. HELENA",
                "Kode_Negara_Alpaha_3" => "SHN",
            ],
            [
                "Id_Negara" => "205",
                "Kode_Negara" => "PM",
                "Nama_Negara" => "ST. PIERRE AND MIQUELON",
                "Kode_Negara_Alpaha_3" => "SPM",
            ],
            [
                "Id_Negara" => "206",
                "Kode_Negara" => "SD",
                "Nama_Negara" => "SUDAN",
                "Kode_Negara_Alpaha_3" => "SDN",
            ],
            [
                "Id_Negara" => "207",
                "Kode_Negara" => "SR",
                "Nama_Negara" => "SURINAME",
                "Kode_Negara_Alpaha_3" => "SUR",
            ],
            [
                "Id_Negara" => "208",
                "Kode_Negara" => "SJ",
                "Nama_Negara" => "SVALBARD AND JAN MAYEN ISLANDS",
                "Kode_Negara_Alpaha_3" => "SJM",
            ],
            [
                "Id_Negara" => "209",
                "Kode_Negara" => "SZ",
                "Nama_Negara" => "SWAZILAND",
                "Kode_Negara_Alpaha_3" => "SWZ",
            ],
            [
                "Id_Negara" => "210",
                "Kode_Negara" => "SE",
                "Nama_Negara" => "SWEDEN",
                "Kode_Negara_Alpaha_3" => "SWE",
            ],
            [
                "Id_Negara" => "211",
                "Kode_Negara" => "CH",
                "Nama_Negara" => "SWITZERLAND",
                "Kode_Negara_Alpaha_3" => "CHE",
            ],
            [
                "Id_Negara" => "212",
                "Kode_Negara" => "SY",
                "Nama_Negara" => "SYRIAN ARAB REPUBLIC",
                "Kode_Negara_Alpaha_3" => "SYR",
            ],
            [
                "Id_Negara" => "213",
                "Kode_Negara" => "TW",
                "Nama_Negara" => "TAIWAN",
                "Kode_Negara_Alpaha_3" => "TWN",
            ],
            [
                "Id_Negara" => "214",
                "Kode_Negara" => "TJ",
                "Nama_Negara" => "TAJIKISTAN",
                "Kode_Negara_Alpaha_3" => "TJK",
            ],
            [
                "Id_Negara" => "215",
                "Kode_Negara" => "TZ",
                "Nama_Negara" => "TANZANIA, UNITED REPUBLIC OF",
                "Kode_Negara_Alpaha_3" => "TZA",
            ],
            [
                "Id_Negara" => "216",
                "Kode_Negara" => "TH",
                "Nama_Negara" => "THAILAND",
                "Kode_Negara_Alpaha_3" => "THA",
            ],
            [
                "Id_Negara" => "217",
                "Kode_Negara" => "TG",
                "Nama_Negara" => "TOGO",
                "Kode_Negara_Alpaha_3" => "TGO",
            ],
            [
                "Id_Negara" => "218",
                "Kode_Negara" => "TK",
                "Nama_Negara" => "TOKELAU",
                "Kode_Negara_Alpaha_3" => "TKL",
            ],
            [
                "Id_Negara" => "219",
                "Kode_Negara" => "TO",
                "Nama_Negara" => "TONGA",
                "Kode_Negara_Alpaha_3" => "TON",
            ],
            [
                "Id_Negara" => "220",
                "Kode_Negara" => "TT",
                "Nama_Negara" => "TRINIDAD AND TOBAGO",
                "Kode_Negara_Alpaha_3" => "TTO",
            ],
            [
                "Id_Negara" => "221",
                "Kode_Negara" => "TN",
                "Nama_Negara" => "TUNISIA",
                "Kode_Negara_Alpaha_3" => "TUN",
            ],
            [
                "Id_Negara" => "222",
                "Kode_Negara" => "TR",
                "Nama_Negara" => "TURKEY",
                "Kode_Negara_Alpaha_3" => "TUR",
            ],
            [
                "Id_Negara" => "223",
                "Kode_Negara" => "TM",
                "Nama_Negara" => "TURKMENISTAN",
                "Kode_Negara_Alpaha_3" => "TKM",
            ],
            [
                "Id_Negara" => "224",
                "Kode_Negara" => "TC",
                "Nama_Negara" => "TURKS AND CAICOS ISLANDS",
                "Kode_Negara_Alpaha_3" => "TCA",
            ],
            [
                "Id_Negara" => "225",
                "Kode_Negara" => "TV",
                "Nama_Negara" => "TUVALU",
                "Kode_Negara_Alpaha_3" => "TUV",
            ],
            [
                "Id_Negara" => "226",
                "Kode_Negara" => "UG",
                "Nama_Negara" => "UGANDA",
                "Kode_Negara_Alpaha_3" => "UGA",
            ],
            [
                "Id_Negara" => "227",
                "Kode_Negara" => "UA",
                "Nama_Negara" => "UKRAINE",
                "Kode_Negara_Alpaha_3" => "UKR",
            ],
            [
                "Id_Negara" => "228",
                "Kode_Negara" => "AE",
                "Nama_Negara" => "UNITED ARAB EMIRATES",
                "Kode_Negara_Alpaha_3" => "ARE",
            ],
            [
                "Id_Negara" => "229",
                "Kode_Negara" => "GB",
                "Nama_Negara" => "UNITED KINGDOM",
                "Kode_Negara_Alpaha_3" => "GBR",
            ],
            [
                "Id_Negara" => "230",
                "Kode_Negara" => "US",
                "Nama_Negara" => "UNITED STATES",
                "Kode_Negara_Alpaha_3" => "USA",
            ],
            [
                "Id_Negara" => "231",
                "Kode_Negara" => "UM",
                "Nama_Negara" => "UNITED STATES MINOR OUTLYING ISLANDS",
                "Kode_Negara_Alpaha_3" => "UMI",
            ],
            [
                "Id_Negara" => "232",
                "Kode_Negara" => "UY",
                "Nama_Negara" => "URUGUAY",
                "Kode_Negara_Alpaha_3" => "URY",
            ],
            [
                "Id_Negara" => "233",
                "Kode_Negara" => "UZ",
                "Nama_Negara" => "UZBEKISTAN",
                "Kode_Negara_Alpaha_3" => "UZB",
            ],
            [
                "Id_Negara" => "234",
                "Kode_Negara" => "VU",
                "Nama_Negara" => "VANUATU",
                "Kode_Negara_Alpaha_3" => "VUT",
            ],
            [
                "Id_Negara" => "235",
                "Kode_Negara" => "VA",
                "Nama_Negara" => "VATICAN CITY STATE",
                "Kode_Negara_Alpaha_3" => "VAT",
            ],
            [
                "Id_Negara" => "236",
                "Kode_Negara" => "VE",
                "Nama_Negara" => "VENEZUELA",
                "Kode_Negara_Alpaha_3" => "VEN",
            ],
            [
                "Id_Negara" => "237",
                "Kode_Negara" => "VN",
                "Nama_Negara" => "VIETNAM",
                "Kode_Negara_Alpaha_3" => "VNM",
            ],
            [
                "Id_Negara" => "238",
                "Kode_Negara" => "VG",
                "Nama_Negara" => "VIRGIN ISLANDS (BRITISH)",
                "Kode_Negara_Alpaha_3" => "VGB",
            ],
            [
                "Id_Negara" => "239",
                "Kode_Negara" => "VI",
                "Nama_Negara" => "VIRGIN ISLANDS (U.S.)",
                "Kode_Negara_Alpaha_3" => "VIR",
            ],
            [
                "Id_Negara" => "240",
                "Kode_Negara" => "WF",
                "Nama_Negara" => "WALLIS AND FUTUNA ISLANDS",
                "Kode_Negara_Alpaha_3" => "WLF",
            ],
            [
                "Id_Negara" => "241",
                "Kode_Negara" => "EH",
                "Nama_Negara" => "WESTERN SAHARA",
                "Kode_Negara_Alpaha_3" => "ESH",
            ],
            [
                "Id_Negara" => "242",
                "Kode_Negara" => "YE",
                "Nama_Negara" => "YEMEN",
                "Kode_Negara_Alpaha_3" => "YEM",
            ],
            [
                "Id_Negara" => "243",
                "Kode_Negara" => "ZR",
                "Nama_Negara" => "ZAIRE",
                "Kode_Negara_Alpaha_3" => "ZAR",
            ],
            [
                "Id_Negara" => "244",
                "Kode_Negara" => "ZM",
                "Nama_Negara" => "ZAMBIA",
                "Kode_Negara_Alpaha_3" => "ZMB",
            ],
            [
                "Id_Negara" => "245",
                "Kode_Negara" => "ZW",
                "Nama_Negara" => "ZIMBABWE",
                "Kode_Negara_Alpaha_3" => "ZWE",
            ],
        ];
        
        foreach($country as $data){
            Country::create([
                'id' => $data['Id_Negara'],
                'code' => $data['Kode_Negara'],
                'name' => $data['Nama_Negara'],
                'code_alpha_3' => $data['Kode_Negara_Alpaha_3'],
            ]);
        }
    }
}
