<?php

namespace Database\Seeders\Lib;

use App\Models\DaftarTersangka;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

use App\Models\Lib\DocumentCategory;

use App\Models\Doc\SuratPerintahPenyelidikanDocument\SuratPerintahPenyelidikanDocument;
use App\Models\Doc\SuratPerintahPenyidikanDocument\SuratPerintahPenyidikanDocument;
use App\Models\Doc\SuratPerintahTugasDocument\SuratPerintahTugasDocument;
use App\Models\Doc\LaporanHasilGelarPerkaraDocument\LaporanHasilGelarPerkaraDocument;
use App\Models\Doc\SuratKetetapanTentangPenetapanTersangkaDocument\SuratKetetapanTentangPenetapanTersangkaDocument;
use App\Models\Doc\SuratPemberitahuanDimulainyaPenyidikanDocument\SuratPemberitahuanDimulainyaPenyidikanDocument;
use App\Models\Doc\DaftarTersangkaDocument\DaftarTersangkaDocument;
use App\Models\Doc\Tahap1Document\Tahap1Document;
use App\Models\Doc\P21Document\P21Document;
use App\Models\Doc\P19Document\P19Document;
use App\Models\Doc\Tahap2Document\Tahap2Document;
use App\Models\Doc\SuratPemberitahuanPerkembanganHasilPenyidikanDocument\SuratPemberitahuanPerkembanganHasilPenyidikanDocument;

class DocumentCategoriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $documentCategories = $this->getDocumentCategories();

        DB::beginTransaction();
        try{
            foreach ($documentCategories as $documentCategory) {
                DocumentCategory::updateOrCreate(
                    [
                        'id' => $documentCategory['id'],
                    ],
                    [
                        'id' => $documentCategory['id'],
                        'code' => $documentCategory['code'],
                        'parent_id' => $documentCategory['parent_id'],
                        'name' => $documentCategory['name'],
                        'category' => $documentCategory['category'],
                        'route' => $documentCategory['route'],
                        'base_route' => $documentCategory['base_route'],
                        'is_digital_signature' => $documentCategory['is_digital_signature'],
                        'model_class' => $documentCategory['model_class'],
                        'alt_code' => $documentCategory['alt_code'],
                        'is_case_finish' => $documentCategory['is_case_finish'],
                    ]
                );
            }

            DB::commit();

            $this->command->info('Document Categories table seeded!');
        }catch(\Exception $e){
            DB::rollback();
            throw $e;
        }
    }

    private function getDocumentCategories(){
        $categoryStage = 'STAGE';
        $categoryType = 'TYPE';
        
        $documentCategories = collect([
            // =====( PENYELIDIKAN )=====
            [
                'id' => '01',
                'code' => 'DCS-0100',
                'parent_id' => NULL,
                'name' => 'PENYELIDIKAN',
                'category' => $categoryStage,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'penyelidikan-documents',
                'is_case_finish' => NULL,
            ],
            [
                'id' => '0101',
                'code' => 'DCT-0101',
                'parent_id' => '01',
                'name' => 'SURAT PERINTAH PENYELIDIKAN',
                'category' => $categoryType,
                'route' => 'doc.surat-perintah-penyelidikan-document.create',
                'base_route' => 'doc.surat-perintah-penyelidikan-document',
                'is_digital_signature' => false,
                'model_class' => get_class(new SuratPerintahPenyelidikanDocument()) . '::class',
                'alt_code' => 'surat-perintah-penyelidikan-document',
                'is_case_finish' => false,

            ],
            [
                'id' => '0102',
                'code' => 'DCT-0102',
                'parent_id' => '01',
                'name' => 'RENCANA PENYELIDIKAN',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'rencana-penyelidikan-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0103',
                'code' => 'DCT-0103',
                'parent_id' => '01',
                'name' => 'BERITA ACARA KLARIFIKASI',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'berita-acara-klarifikasi-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0104',
                'code' => 'DCT-0104',
                'parent_id' => '01',
                'name' => 'BERITA ACARA PEMERIKSAAN DI TKP',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'berita-acara-pemeriksaan-di-tkp-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0105',
                'code' => 'DCT-0105',
                'parent_id' => '01',
                'name' => 'BERITA ACARA PENEMUAN DAN PENYITAAN BARANG BUKTI DI TKP',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'berita-acara-penemuan-dan-penyitaan-barang-bukti-di-tkp-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0106',
                'code' => 'DCT-0106',
                'parent_id' => '01',
                'name' => 'BERITA ACARA PENGAMBILAN DARAH DI TKP',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'berita-acara-pengambilan-darah-di-tkp-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0107',
                'code' => 'DCT-0107',
                'parent_id' => '01',
                'name' => 'BERITA ACARA PENGAMBILAN SPERMA DI TKP',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'berita-acara-pengambilan-sperma-di-tkp-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0108',
                'code' => 'DCT-0108',
                'parent_id' => '01',
                'name' => 'BERITA ACARA PENGAMBILAN JEJAK / SIDIK JARI DI TKP',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'berita-acara-pengambilan-jejak-sidik-jari-di-tkp-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0109',
                'code' => 'DCT-0109',
                'parent_id' => '01',
                'name' => 'BERITA ACARA PENGAMBILAN PEMOTRETAN DI TKP',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'berita-acara-pengambilan-pemotretan-di-tkp-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0110',
                'code' => 'DCT-0110',
                'parent_id' => '01',
                'name' => 'LAPORAN HASIL PENYELIDIKAN',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'laporan-hasil-penyelidikan-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0111',
                'code' => 'DCT-0111',
                'parent_id' => '01',
                'name' => 'SURAT UNDANGAN KLARIFIKASI',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-undangan-klarifikasi-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0112',
                'code' => 'DCT-0112',
                'parent_id' => '01',
                'name' => 'SURAT KETETAPAN PENGHENTIAN PENYELIDIKAN',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-ketetapan-penghentian-penyelidikan-document',
                'is_case_finish' => false,
            ],
            // =====( END PENYELIDIKAN )=====
            
            // =====( PENYIDIKAN )=====
            [
                'id' => '02',
                'code' => 'DCS-0200',
                'parent_id' => NULL,
                'name' => 'PENYIDIKAN',
                'category' => $categoryStage,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'penyidikan-documents',
                'is_case_finish' => NULL,
            ],
            [
                'id' => '0201',
                'code' => 'DCT-0201',
                'parent_id' => '02',
                'name' => 'SURAT PERINTAH PENYIDIKAN',
                'category' => $categoryType,
                'route' => 'doc.surat-perintah-penyidikan-document.create',
                'base_route' => 'doc.surat-perintah-penyidikan-document',
                'is_digital_signature' => false,
                'model_class' => get_class(new SuratPerintahPenyidikanDocument()) . '::class',
                'alt_code' => 'surat-perintah-penyidikan-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0202',
                'code' => 'DCT-0202',
                'parent_id' => '02',
                'name' => 'RENCANA PENYIDIKAN',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'rencana-penyidikan-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0203',
                'code' => 'DCT-0203',
                'parent_id' => '02',
                'name' => 'BERITA ACARA PEMERIKSAAN',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'berita-acara-pemeriksaan-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0204',
                'code' => 'DCT-0204',
                'parent_id' => '02',
                'name' => 'SURAT PEMBERITAHUAN DIMULAINYA PENYIDIKAN',
                'category' => $categoryType,
                'route' => "doc.surat-pemberitahuan-dimulainya-penyidikan-document.create",
                'base_route' => 'doc.surat-pemberitahuan-dimulainya-penyidikan-document',
                'is_digital_signature' => true,
                'model_class' => get_class(new SuratPemberitahuanDimulainyaPenyidikanDocument()) . '::class',
                'alt_code' => 'surat-pemberitahuan-dimulainya-penyidikan-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0205',
                'code' => 'DCT-0205',
                'parent_id' => '02',
                'name' => 'SURAT PERINTAH PENGHENTIAN PENYIDIKAN',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-perintah-penghentian-penyidikan-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0206',
                'code' => 'DCT-0206',
                'parent_id' => '02',
                'name' => 'SURAT KETETAPAN PENGHENTIAN PENYIDIKAN',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-ketetapan-penghentian-penyidikan-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0207',
                'code' => 'DCT-0207',
                'parent_id' => '02',
                'name' => 'SURAT PERMINTAAN CEKAL',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-permintaan-cekal-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0208',
                'code' => 'DCT-0208',
                'parent_id' => '02',
                'name' => 'SURAT PANGGILAN SAKSI',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-panggilan-saksi-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0209',
                'code' => 'DCT-0209',
                'parent_id' => '02',
                'name' => 'SURAT PANGGILAN TERSANGKA',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-panggilan-tersangka-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0210',
                'code' => 'DCT-0210',
                'parent_id' => '02',
                'name' => 'SURAT PANGGILAN SAKSI AHLI',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-panggilan-saksi-ahli-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0211',
                'code' => 'DCT-0211',
                'parent_id' => '02',
                'name' => 'SURAT PEMBERITAHUAN UPAYA DIVERSI',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-pemberitahuan-upaya-diversi-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0212',
                'code' => 'DCT-0212',
                'parent_id' => '02',
                'name' => 'SURAT PERMOHONAN PENETAPAN KESEPAKATAN DIVERSI',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-permohonan-penetapan-kesepakatan-diversi-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0213',
                'code' => 'DCT-0213',
                'parent_id' => '02',
                'name' => 'SURAT KESEPAKATAN DIVERSI',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-kesepakatan-diversi-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0214',
                'code' => 'DCT-0214',
                'parent_id' => '02',
                'name' => 'SURAT PERMOHONAN PENELITIAN KEMASYARAKATAN',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-permohonan-penelitian-kemasyarakatan-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0215',
                'code' => 'DCT-0215',
                'parent_id' => '02',
                'name' => 'SURAT KETETAPAN TENTANG PENETAPAN TERSANGKA',
                'category' => $categoryType,
                'route' => "doc.surat-ketetapan-tentang-penetapan-tersangka-document.create",
                'base_route' => 'doc.surat-ketetapan-tentang-penetapan-tersangka-document',
                'is_digital_signature' => false,
                'model_class' => get_class(new SuratKetetapanTentangPenetapanTersangkaDocument()) . '::class',
                'alt_code' => 'surat-ketetapan-tentang-penetapan-tersangka-document',
                'is_case_finish' => false,
            ],
            // =====( END PENYIDIKAN )=====

            // =====( PENANGKAPAN )=====
            [
                'id' => '03',
                'code' => 'DCS-0300',
                'parent_id' => NULL,
                'name' => 'PENANGKAPAN',
                'category' => $categoryStage,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'penangkapan-documents',
                'is_case_finish' => NULL,
            ],
            [
                'id' => '0301',
                'code' => 'DCT-0301',
                'parent_id' => '03',
                'name' => 'SURAT PERINTAH PENANGKAPAN',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-perintah-penangkapan-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0302',
                'code' => 'DCT-0302',
                'parent_id' => '03',
                'name' => 'SURAT DAFTAR PENCARIAN ORANG',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-daftar-pencarian-orang-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0303',
                'code' => 'DCT-0303',
                'parent_id' => '03',
                'name' => 'SURAT PERINTAH TUGAS PENANGKAPAN',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-perintah-tugas-penangkapan-document',
                'is_case_finish' => false,
            ],
            // =====( END PENANGKAPAN )=====

            // =====( PENGGELEDAHAN )=====
            [
                'id' => '04',
                'code' => 'DCS-0400',
                'parent_id' => NULL,
                'name' => 'PENGGELEDAHAN',
                'category' => $categoryStage,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'penggeledahan-documents',
                'is_case_finish' => NULL,
            ],
            [
                'id' => '0401',
                'code' => 'DCT-0401',
                'parent_id' => '04',
                'name' => 'SURAT PERINTAH PENGGELEDAHAN RUMAH TINGGAL/ TEMPAT-TEMPAT TERTUTUP LAINNYA',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-perintah-penggeledahan-rumah-tinggal-tempat-tempat-tertutup-lainnya-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0402',
                'code' => 'DCT-0402',
                'parent_id' => '04',
                'name' => 'SURAT PERINTAH PENGGELEDAHAN ALAT ANGKUTAN',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-perintah-penggeledahan-alat-angkutan-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0403',
                'code' => 'DCT-0403',
                'parent_id' => '04',
                'name' => 'SURAT PERINTAH PENGGELEDAHAN PAKAIAN BADAN',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-perintah-penggeledahan-pakaian-badan-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0404',
                'code' => 'DCT-0404',
                'parent_id' => '04',
                'name' => 'SURAT PERMINTAAN IZIN PENGGELEDAHAN',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-permintaan-izin-penggeledahan-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0405',
                'code' => 'DCT-0405',
                'parent_id' => '04',
                'name' => 'SURAT LAPORAN GUNA MEMPEROLEH PERSETUJUAN PENGGELEDAHAN KEPADA KETUA PENGADILAN NEGERI',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-laporan-guna-memperoleh-persetujuan-penggeledahan-kepada-ketua-pengadilan-negeri-document',
                'is_case_finish' => false,
            ],
            // =====( END PENGGELEDAHAN )=====

            // =====( PENYITAAN )=====
            [
                'id' => '05',
                'code' => 'DCS-0500',
                'parent_id' => NULL,
                'name' => 'PENYITAAN',
                'category' => $categoryStage,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'penyitaan-documents',
                'is_case_finish' => NULL,
            ],
            [
                'id' => '0501',
                'code' => 'DCT-0501',
                'parent_id' => '05',
                'name' => 'SURAT PERMINTAAN IZIN / IZIN KHUSUS PENYITAAN KEPADA KETUA PENGADILAN NEGERI',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-permintaan-izin-izin-khusus-penyitaan-kepada-ketua-pengadilan-negeri-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0502',
                'code' => 'DCT-0502',
                'parent_id' => '05',
                'name' => 'SURAT PERINTAH PENYITAAN',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-perintah-penyitaan-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0503',
                'code' => 'DCT-0503',
                'parent_id' => '05',
                'name' => 'SURAT PERINTAH PENGEMBALIAN BARANG BUKTI',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-perintah-pengembalian-barang-bukti-document',
                'is_case_finish' => false,
            ],
            // =====( END PENYITAAN )=====

            // =====( PENAHANAN )=====
            [
                'id' => '06',
                'code' => 'DCS-0600',
                'parent_id' => NULL,
                'name' => 'PENAHANAN',
                'category' => $categoryStage,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'penahanan-documents',
                'is_case_finish' => NULL,
            ],
            [
                'id' => '0601',
                'code' => 'DCT-0601',
                'parent_id' => '06',
                'name' => 'SURAT PERINTAH PENAHANAN',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-perintah-penahanan-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0602',
                'code' => 'DCT-0602',
                'parent_id' => '06',
                'name' => 'BERITA ACARA SERAH TERIMA TERSANGKA DAN BARANG BUKTI',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'berita-acara-serah-terima-tersangka-dan-barang-bukti-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0603',
                'code' => 'DCT-0603',
                'parent_id' => '06',
                'name' => 'BERITA ACARA PENAHANAN',
                'category' => $categoryType,
                'route' => 'doc.berita-acara-penahanan-document.create',
                'base_route' => 'doc.berita-acara-penahanan-document',
                'is_digital_signature' => true,
                'model_class' => 'App\Models\Doc\BeritaAcaraPenahananDocument\BeritaAcaraPenahananDocument',
                'alt_code' => 'berita-acara-penahanan-document',
                'is_case_finish' => false,
            ],
            // =====( END PENAHANAN )=====

            // =====( GENERAL )=====
            [
                'id' => '07',
                'code' => 'DCS-0700',
                'parent_id' => NULL,
                'name' => 'GENERAL',
                'category' => $categoryStage,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'general-documents',
                'is_case_finish' => NULL,
            ],
            [
                'id' => '0701',
                'code' => 'DCT-0701',
                'parent_id' => '07',
                'name' => 'UNDANGAN GELAR PERKARA',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'undangan-gelar-perkara-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0702',
                'code' => 'DCT-0702',
                'parent_id' => '07',
                'name' => 'SURAT PERINTAH TUGAS',
                'category' => $categoryType,
                'route' => 'doc.surat-perintah-tugas-document.create',
                'base_route' => 'doc.surat-perintah-tugas-document',
                'is_digital_signature' => false,
                'model_class' => get_class(new SuratPerintahTugasDocument()) . '::class',
                'alt_code' => 'surat-perintah-tugas-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0703',
                'code' => 'DCT-0703',
                'parent_id' => '07',
                'name' => 'SURAT KUASA',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-kuasa-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0704',
                'code' => 'DCT-0704',
                'parent_id' => '07',
                'name' => 'SURAT PENUNJUKAN PENASIHAT HUKUM',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-penunjukan-penasihat-hukum-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0705',
                'code' => 'DCT-0705',
                'parent_id' => '07',
                'name' => 'DAFTAR PENCARIAN BARANG',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'daftar-pencarian-barang-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0706',
                'code' => 'DCT-0706',
                'parent_id' => '07',
                'name' => 'LAPORAN HASIL GELAR PERKARA',
                'category' => $categoryType,
                'route' => 'doc.laporan-hasil-gelar-perkara-document.create',
                'base_route' => 'doc.laporan-hasil-gelar-perkara-document',
                'is_digital_signature' => false,
                'model_class' => get_class(new LaporanHasilGelarPerkaraDocument()) . '::class',
                'alt_code' => 'laporan-hasil-gelar-perkara-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0707',
                'code' => 'DCT-0707',
                'parent_id' => '07',
                'name' => 'SURAT PERMINTAAN BLOKIR REKENING BANK',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-permintaan-blokir-rekening-bank-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0708',
                'code' => 'DCT-0708',
                'parent_id' => '07',
                'name' => 'SURAT PERMINTAAN BUKA BLOKIR REKENING BANK',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-permintaan-buka-blokir-rekening-bank-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0709',
                'code' => 'DCT-0709',
                'parent_id' => '07',
                'name' => 'SURAT PEMBERITAHUAN PERKEMBANGAN HASIL PENYIDIKAN (SP2HP)',
                'category' => $categoryType,
                'route' => 'doc.surat-pemberitahuan-perkembangan-hasil-penyidikan-document.create',
                'base_route' => 'doc.surat-pemberitahuan-perkembangan-hasil-penyidikan-document',
                'is_digital_signature' => false,
                'model_class' => get_class(new SuratPemberitahuanPerkembanganHasilPenyidikanDocument()) . '::class',
                'alt_code' => 'surat-pemberitahuan-perkembangan-hasil-penyidikan-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0710',
                'code' => 'DCT-0710',
                'parent_id' => '07',
                'name' => 'SURAT PEMBERITAHUAN PERKEMBANGAN HASIL PENYIDIKAN (SP2HP) - A2',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-pemberitahuan-perkembangan-hasil-penyidikan-document-A2',
                'is_case_finish' => false,
            ],
            [
                'id' => '0711',
                'code' => 'DCT-0711',
                'parent_id' => '07',
                'name' => 'SURAT PEMBERITAHUAN PERKEMBANGAN HASIL PENYIDIKAN (SP2HP) - A3',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-pemberitahuan-perkembangan-hasil-penyidikan-document-A3',
                'is_case_finish' => false,
            ],
            [
                'id' => '0712',
                'code' => 'DCT-0712',
                'parent_id' => '07',
                'name' => 'SURAT PEMBERITAHUAN PERKEMBANGAN HASIL PENYIDIKAN (SP2HP) - A5',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-pemberitahuan-perkembangan-hasil-penyidikan-document-A5',
                'is_case_finish' => false,
            ],
            [
                'id' => '0713',
                'code' => 'DCT-0713',
                'parent_id' => '07',
                'name' => 'SURAT KETETAPAN PENASIHAT HUKUM',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-ketetapan-penasihat-hukum-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0714',
                'code' => 'DCT-0714',
                'parent_id' => '07',
                'name' => 'SURAT PERMINTAAN VISUM ET REPERTUM/VISUM ET PSIKIATRIKUM',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-permintaan-visum-et-repertum-visum-et-psikiatrikum-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0715',
                'code' => 'DCT-0715',
                'parent_id' => '07',
                'name' => 'SURAT PENCABUTAN DAFTAR PENCARIAN BARANG',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-pencabutan-daftar-pencarian-barang-document',
                'is_case_finish' => false,
            ],
            // =====( END GENERAL )=====

            // =====( PEMBERKASAN )=====
            [
                'id' => '08',
                'code' => 'DCS-0800',
                'parent_id' => NULL,
                'name' => 'PEMBERKASAN',
                'category' => $categoryStage,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'pemberkasan-documents',
                'is_case_finish' => NULL,
            ],
            [
                'id' => '0801',
                'code' => 'DCT-0801',
                'parent_id' => '08',
                'name' => 'RESUME',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'resume-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0802',
                'code' => 'DCT-0802',
                'parent_id' => '08',
                'name' => 'DAFTAR SAKSI',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'daftar-saksi-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0803',
                'code' => 'DCT-0803',
                'parent_id' => '08',
                'name' => 'DAFTAR AHLI',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'daftar-ahli-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0804',
                'code' => 'DCT-0804',
                'parent_id' => '08',
                'name' => 'DAFTAR TERSANGKA',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' =>  NULL,
                'alt_code' => 'daftar-tersangka-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0805',
                'code' => 'DCT-0805',
                'parent_id' => '08',
                'name' => 'TAHAP I',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' =>  NULL,
                'alt_code' => 'tahap-1-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0806',
                'code' => 'DCT-0806',
                'parent_id' => '08',
                'name' => 'TAHAP II',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' =>  NULL,
                'alt_code' => 'tahap-2-document',
                'is_case_finish' => true,
            ],
            [
                'id' => '0807',
                'code' => 'DCT-0807',
                'parent_id' => '08',
                'name' => 'P19',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' =>  NULL,
                'alt_code' => 'p19-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0808',
                'code' => 'DCT-0808',
                'parent_id' => '08',
                'name' => 'P21',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' =>  NULL,
                'alt_code' => 'p21-document',
                'is_case_finish' => false,
            ],
            // =====( END PEMBERKASAN )=====

             // =====( SATKER LAIN )=====
             [
                'id' => '09',
                'code' => 'DCS-0900',
                'parent_id' => NULL,
                'name' => 'SATKER LAIN',
                'category' => $categoryStage,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'satker-lain-documents',
                'is_case_finish' => NULL,
            ],
            [
                'id' => '0901',
                'code' => 'DCT-0901',
                'parent_id' => '09',
                'name' => 'SURAT PERMOHONAN PEMERIKSAAN LAPORAN INTELEJEN',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-permohonan-pemeriksaan-laporan-intelejen-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0902',
                'code' => 'DCT-0902',
                'parent_id' => '09',
                'name' => 'SURAT PERMOHONAN PERPANJANGAN PENANGKAPAN 7 HARI KE PENGADILAN',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-permohonan-perpanjangan-penangkapan-7-hari-ke-pengadilan-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0903',
                'code' => 'DCT-0903',
                'parent_id' => '09',
                'name' => 'SURAT PERMOHONAN PERPANJANGAN PENAHANAN 60 HARI KE KEJAKSAAN',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-permohonan-perpanjangan-penahanan-60-hari-ke-kejaksaan-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0904',
                'code' => 'DCT-0904',
                'parent_id' => '09',
                'name' => 'SURAT PERMOHONAN PERPANJANGAN PENAHANAN 20 HARI KE PENGADILAN',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-permohonan-perpanjangan-penahanan-20-hari-ke-pengadilan-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0905',
                'code' => 'DCT-0905',
                'parent_id' => '09',
                'name' => 'SURAT PERINTAH PENYIDIKAN TIPIRING',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-perintah-penyidikan-tipiring-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0906',
                'code' => 'DCT-0906',
                'parent_id' => '09',
                'name' => 'BERITA ACARA PEMERIKSAAN CEPAT',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'berita-acara-pemeriksaan-cepat-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0907',
                'code' => 'DCT-0907',
                'parent_id' => '09',
                'name' => 'SURAT PENGIRIMAN BERKAS PERKARA',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'surat-pengiriman-berkas-perkara-document',
                'is_case_finish' => false,
            ],
            [
                'id' => '0908',
                'code' => 'DCT-0908',
                'parent_id' => '09',
                'name' => 'GAMBAR SITUASI PENGEJARAN DAN PENGHENTIAN',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'gambar-situasi-pengejaran-dan-penghentian-document',
                'is_case_finish' => false,
            ],
            // =====( END SATKER LAIN )=====

            // =====( SATKER LAIN )=====
            [
                'id' => '10',
                'code' => 'DCS-1000',
                'parent_id' => NULL,
                'name' => 'PENYELESAIAN',
                'category' => $categoryStage,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'penyelesaian-documents',
                'is_case_finish' => NULL,
            ],
            [
                'id' => '1001',
                'code' => 'DCT-1001',
                'parent_id' => '10',
                'name' => 'RESTORATIVE JUSTICE',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'restorative-justice-document',
                'is_case_finish' => true,
            ],
            [
                'id' => '1002',
                'code' => 'DCT-1002',
                'parent_id' => '10',
                'name' => 'POM/TNI',
                'category' => $categoryType,
                'route' => NULL,
                'base_route' => NULL,
                'is_digital_signature' => false,
                'model_class' => NULL,
                'alt_code' => 'pom-tni-document',
                'is_case_finish' => true,
            ],
        ]);

        return collect($documentCategories);
    }
}
