<?php

namespace Database\Seeders\Lib;

use App\Models\Lib\Prison;
use Illuminate\Database\Seeder;

class PrisonTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $prisons = [
                ["provinsi" => "Aceh", "nama" => "Lapas Kelas IIA Banda Aceh", "cabang" => "Lambaro"],
                ["provinsi" => "Aceh", "nama" => "Lapas Kelas IIB Meulaboh", "cabang" => "Aceh Barat"],
                ["provinsi" => "Aceh", "nama" => "Lapas Kelas IIB Lhokseumawe", "cabang" => "Lhokseumawe"],
                ["provinsi" => "Aceh", "nama" => "Lapas Kelas IIB Langsa", "cabang" => "Langsa"],
                ["provinsi" => "Aceh", "nama" => "Lapas Kelas IIB Idie", "cabang" => "Aceh Timur"],
                ["provinsi" => "Aceh", "nama" => "Lapas Kelas IIB Kutacane", "cabang" => "Aceh Tenggara"],
                ["provinsi" => "Aceh", "nama" => "Lapas Kelas IIB Blang Pidie", "cabang" => "Aceh Barat Daya"],
                ["provinsi" => "Aceh", "nama" => "Lapas Kelas IIB Kuala Simpang", "cabang" => "Aceh Tamiang"],
                ["provinsi" => "Aceh", "nama" => "Lapas Kelas IIB Meureudu", "cabang" => "Pidie Jaya"],
                ["provinsi" => "Aceh", "nama" => "Lapas Narkotika Kelas IIB Langsa", "cabang" => "Langsa"],
                ["provinsi" => "Aceh", "nama" => "Lapas Perempuan Kelas IIB Sigli", "cabang" => "Pidie"],
                ["provinsi" => "Aceh", "nama" => "Lapas Kelas III Lhoknga", "cabang" => "Aceh Besar"],
                ["provinsi" => "Aceh", "nama" => "LPKA Kelas II Banda Aceh", "cabang" => "Aceh Besar"],
                ["provinsi" => "Aceh", "nama" => "Rutan Kelas IIB Banda Aceh", "cabang" => "Kajhu"],
                ["provinsi" => "Aceh", "nama" => "Rutan Kelas IIB Jantho", "cabang" => "Aceh Besar"],
                ["provinsi" => "Aceh", "nama" => "Rutan Kelas IIB Sigli", "cabang" => "Pidie"],
                ["provinsi" => "Aceh", "nama" => "Rutan Kelas IIB Takengon", "cabang" => "Aceh Tengah"],
                ["provinsi" => "Aceh", "nama" => "Rutan Kelas IIB Tapaktuan", "cabang" => "Aceh Selatan"],
                ["provinsi" => "Aceh", "nama" => "Rutan Kelas IIB Bireuen", "cabang" => "Bireuen"],
                ["provinsi" => "Aceh", "nama" => "Rutan Kelas IIB Blangkejeren", "cabang" => "Gayo Lues"],
                ["provinsi" => "Aceh", "nama" => "Rutan Kelas IIB Calang", "cabang" => "Aceh Jaya"],
                ["provinsi" => "Aceh", "nama" => "Rutan Kelas IIB Sinabang", "cabang" => "Simeulue"],
                ["provinsi" => "Aceh", "nama" => "Rutan Kelas IIB Sabang", "cabang" => "Kota Sabang"],
                ["provinsi" => "Aceh", "nama" => "Rutan Kelas IIB Singkil", "cabang" => "Aceh Singkil"],
                ["provinsi" => "Aceh", "nama" => "Rutan Kelas IIB Kutacane", "cabang" => "Aceh Tenggara"],
                ["provinsi" => "Aceh", "nama" => "Rutan Kelas IIB Blangpidie", "cabang" => "Aceh Barat Daya"],
                ["provinsi" => "Sumatera Utara", "nama" => "Lapas Kelas I Medan", "cabang" => "Tanjung Gusta"],
                ["provinsi" => "Sumatera Utara", "nama" => "Lapas Kelas IIA Binjai", "cabang" => "Binjai"],
                ["provinsi" => "Sumatera Utara", "nama" => "Lapas Kelas IIA Pematangsiantar", "cabang" => "Simalungun"],
                ["provinsi" => "Sumatera Utara", "nama" => "Lapas Kelas IIA Tanjung Balai", "cabang" => "Asahan"],
                ["provinsi" => "Sumatera Utara", "nama" => "Lapas Kelas IIA Sibolga", "cabang" => "Tapanuli Tengah"],
                ["provinsi" => "Sumatera Utara", "nama" => "Lapas Kelas IIA Labuhan Ruku", "cabang" => "Batu Bara"],
                ["provinsi" => "Sumatera Utara", "nama" => "Lapas Kelas IIB Lubuk Pakam", "cabang" => "Deli Serdang"],
                ["provinsi" => "Sumatera Utara", "nama" => "Lapas Kelas IIB Tebing Tinggi", "cabang" => "Tebing Tinggi"],
                ["provinsi" => "Sumatera Utara", "nama" => "Lapas Kelas IIB Padangsidimpuan", "cabang" => "Tapanuli Selatan"],
                ["provinsi" => "Sumatera Utara", "nama" => "Lapas Kelas IIB Panyabungan", "cabang" => "Mandailing Natal"],
                ["provinsi" => "Sumatera Utara", "nama" => "Lapas Kelas IIB Siborong-borong", "cabang" => "Tapanuli Utara"],
                ["provinsi" => "Sumatera Utara", "nama" => "Lapas Kelas IIB Tanjung Pura", "cabang" => "Langkat"],
                ["provinsi" => "Sumatera Utara", "nama" => "Lapas Kelas IIB Kotapinang", "cabang" => "Labuhanbatu Selatan"],
                ["provinsi" => "Sumatera Utara", "nama" => "Lapas Kelas IIB Sidikalang", "cabang" => "Dairi"],
                ["provinsi" => "Sumatera Utara", "nama" => "Lapas Kelas IIB Barus", "cabang" => "Tapanuli Tengah"],
                ["provinsi" => "Sumatera Utara", "nama" => "Lapas Kelas III Labuhan Bilik", "cabang" => "Labuhanbatu"],
                ["provinsi" => "Sumatera Utara", "nama" => "Lapas Kelas III Gunung Tua", "cabang" => "Padang Lawas Utara"],
                ["provinsi" => "Sumatera Utara", "nama" => "Lapas Kelas III Teluk Dalam", "cabang" => "Nias Selatan"],
                ["provinsi" => "Sumatera Utara", "nama" => "Lapas Narkotika Kelas IIA Pematangsiantar", "cabang" => "Simalungun"],
                ["provinsi" => "Sumatera Utara", "nama" => "Lapas Narkotika Kelas IIA Langkat", "cabang" => "Langkat"],
                ["provinsi" => "Sumatera Utara", "nama" => "Lapas Perempuan Kelas IIA Medan", "cabang" => "Tanjung Gusta"],
                ["provinsi" => "Sumatera Utara", "nama" => "LPKA Kelas I Medan", "cabang" => "Tanjung Gusta"],
                ["provinsi" => "Sumatera Utara", "nama" => "Rutan Kelas I Medan", "cabang" => "Tanjung Gusta"],
                ["provinsi" => "Sumatera Utara", "nama" => "Rutan Kelas I Labuhan Deli", "cabang" => "Deli Serdang"],
                ["provinsi" => "Sumatera Utara", "nama" => "Rutan Kelas I Tanjung Gusta", "cabang" => "Medan"],
                ["provinsi" => "Sumatera Utara", "nama" => "Rutan Kelas IIB Kabanjahe", "cabang" => "Karo"],
                ["provinsi" => "Sumatera Utara", "nama" => "Rutan Kelas IIB Tarutung", "cabang" => "Tapanuli Utara"],
                ["provinsi" => "Sumatera Utara", "nama" => "Rutan Kelas IIB Sidikalang", "cabang" => "Dairi"],
                ["provinsi" => "Sumatera Utara", "nama" => "Rutan Kelas IIB Sibuhuan", "cabang" => "Padang Lawas"],
                ["provinsi" => "Sumatera Utara", "nama" => "Rutan Kelas IIB Gunung Sitoli", "cabang" => "Nias"],
                ["provinsi" => "Sumatera Utara", "nama" => "Rutan Kelas IIB Balige", "cabang" => "Toba Samosir"],
                ["provinsi" => "Sumatera Utara", "nama" => "Rutan Kelas IIB Sipirok", "cabang" => "Tapanuli Selatan"],
                ["provinsi" => "Sumatera Utara", "nama" => "Rutan Kelas IIB Pangkalan Brandan", "cabang" => "Langkat"],
                ["provinsi" => "Sumatera Utara", "nama" => "Rutan Kelas IIB Gunung Tua", "cabang" => "Padang Lawas Utara"],
                ["provinsi" => "Sumatera Utara", "nama" => "Rutan Kelas IIB Tanjung Pura", "cabang" => "Langkat"],
                ["provinsi" => "Sumatera Utara", "nama" => "Rutan Kelas IIB Labuhan Ruku", "cabang" => "Batu Bara"],
                ["provinsi" => "Sumatera Utara", "nama" => "Rutan Kelas IIB Natal", "cabang" => "Mandailing Natal"],
                ["provinsi" => "Sumatera Utara", "nama" => "Rutan Kelas IIB Labuhan Bilik", "cabang" => "Labuhanbatu"],
                ["provinsi" => "Sumatera Barat", "nama" => "Lapas Kelas IIA Padang", "cabang" => "Muaro"],
                ["provinsi" => "Sumatera Barat", "nama" => "Lapas Kelas IIA Bukittinggi", "cabang" => "Biaro"],
                ["provinsi" => "Sumatera Barat", "nama" => "Lapas Kelas IIB Pariaman", "cabang" => "Pariaman"],
                ["provinsi" => "Sumatera Barat", "nama" => "Lapas Kelas IIB Payakumbuh", "cabang" => "Payakumbuh"],
                ["provinsi" => "Sumatera Barat", "nama" => "Lapas Kelas IIB Solok", "cabang" => "Solok"],
                ["provinsi" => "Sumatera Barat", "nama" => "Lapas Kelas IIB Muaro Sijunjung", "cabang" => "Sijunjung"],
                ["provinsi" => "Sumatera Barat", "nama" => "Lapas Kelas IIB Lubuk Basung", "cabang" => "Agam"],
                ["provinsi" => "Sumatera Barat", "nama" => "Lapas Perempuan Kelas IIB Padang", "cabang" => "Anak Air"],
                ["provinsi" => "Sumatera Barat", "nama" => "LPKA Kelas IIA Tanjung Pati", "cabang" => "Lima Puluh Kota"],
                ["provinsi" => "Sumatera Barat", "nama" => "Rutan Kelas IIB Padang", "cabang" => "Anak Air"],
                ["provinsi" => "Sumatera Barat", "nama" => "Rutan Kelas IIB Batusangkar", "cabang" => "Tanah Datar"],
                ["provinsi" => "Sumatera Barat", "nama" => "Rutan Kelas IIB Painan", "cabang" => "Pesisir Selatan"],
                ["provinsi" => "Sumatera Barat", "nama" => "Rutan Kelas IIB Lubuk Sikaping", "cabang" => "Pasaman"],
                ["provinsi" => "Sumatera Barat", "nama" => "Rutan Kelas IIB Sawahlunto", "cabang" => "Sawahlunto"],
                ["provinsi" => "Sumatera Barat", "nama" => "Rutan Kelas IIB Maninjau", "cabang" => "Agam"],
                ["provinsi" => "Sumatera Barat", "nama" => "Rutan Kelas IIB Talu", "cabang" => "Pasaman Barat"],
                ["provinsi" => "Sumatera Barat", "nama" => "Rutan Kelas IIB Lubuk Alung", "cabang" => "Padang Pariaman"],
                ["provinsi" => "Sumatera Barat", "nama" => "Lapas Kelas III Suliki", "cabang" => "Lima Puluh Kota"],
                ["provinsi" => "Sumatera Barat", "nama" => "Lapas Kelas IIB Dharmasraya", "cabang" => "Dharmasraya"],
                ["provinsi" => "Sumatera Barat", "nama" => "Lapas Kelas III Alahan Panjang", "cabang" => "Solok"],
                ["provinsi" => "Riau", "nama" => "Lapas Kelas IIA Pekanbaru", "cabang" => "Pekanbaru"],
                ["provinsi" => "Riau", "nama" => "Lapas Kelas IIA Tembilahan", "cabang" => "Indragiri Hilir"],
                ["provinsi" => "Riau", "nama" => "Lapas Kelas IIA Bengkalis", "cabang" => "Bengkalis"],
                ["provinsi" => "Riau", "nama" => "Lapas Kelas IIB Pasir Pengaraian", "cabang" => "Rokan Hulu"],
                ["provinsi" => "Riau", "nama" => "Lapas Kelas IIB Bangkinang", "cabang" => "Kampar"],
                ["provinsi" => "Riau", "nama" => "Lapas Kelas IIB Teluk Kuantan", "cabang" => "Kuantan Singingi"],
                ["provinsi" => "Riau", "nama" => "Lapas Kelas IIB Selat Panjang", "cabang" => "Kepulauan Meranti"],
                ["provinsi" => "Riau", "nama" => "Lapas Kelas IIB Bagansiapiapi", "cabang" => "Rokan Hilir"],
                ["provinsi" => "Riau", "nama" => "Lapas Narkotika Kelas IIB Rumbai", "cabang" => "Pekanbaru"],
                ["provinsi" => "Riau", "nama" => "Lapas Perempuan Kelas IIA Pekanbaru", "cabang" => "Pekanbaru"],
                ["provinsi" => "Riau", "nama" => "LPKA Kelas II Pekanbaru", "cabang" => "Pekanbaru"],
                ["provinsi" => "Riau", "nama" => "Rutan Kelas I Pekanbaru", "cabang" => "Sialang Bungkuk"],
                ["provinsi" => "Riau", "nama" => "Rutan Kelas IIB Dumai", "cabang" => "Dumai"],
                ["provinsi" => "Riau", "nama" => "Rutan Kelas IIB Rengat", "cabang" => "Indragiri Hulu"],
                ["provinsi" => "Riau", "nama" => "Rutan Kelas IIB Siak Sri Indrapura", "cabang" => "Siak"],
                ["provinsi" => "Riau", "nama" => "Lapas Kelas IIB Gobah", "cabang" => "Pekanbaru"],
                ["provinsi" => "Jambi", "nama" => "Lapas Kelas IIA Jambi", "cabang" => "Jambi"],
                ["provinsi" => "Jambi", "nama" => "Lapas Kelas IIB Muara Bulian", "cabang" => "Batanghari"],
                ["provinsi" => "Jambi", "nama" => "Lapas Kelas IIB Muara Bungo", "cabang" => "Bungo"],
                ["provinsi" => "Jambi", "nama" => "Lapas Kelas IIB Bangko", "cabang" => "Merangin"],
                ["provinsi" => "Jambi", "nama" => "Lapas Kelas IIB Sarolangun", "cabang" => "Sarolangun"],
                ["provinsi" => "Jambi", "nama" => "Lapas Narkotika Kelas IIB Muara Sabak", "cabang" => "Tanjung Jabung Timur"],
                ["provinsi" => "Jambi", "nama" => "Lapas Perempuan Kelas IIB Jambi", "cabang" => "Muaro Jambi"],
                ["provinsi" => "Jambi", "nama" => "Rutan Kelas IIB Jambi", "cabang" => "Jambi"],
                ["provinsi" => "Jambi", "nama" => "Rutan Kelas IIB Kuala Tungkal", "cabang" => "Tanjung Jabung Barat"],
                ["provinsi" => "Jambi", "nama" => "Rutan Kelas IIB Sungai Penuh", "cabang" => "Sungai Penuh"],
                ["provinsi" => "Jambi", "nama" => "Lapas Kelas IIB Tebo", "cabang" => "Tebo"],
                ["provinsi" => "Jambi", "nama" => "Rutan Kelas IIB Bangko", "cabang" => "Merangin"],
                ["provinsi" => "Sumatera Selatan", "nama" => "Lapas Kelas I Palembang", "cabang" => "Merah Mata"],
                ["provinsi" => "Sumatera Selatan", "nama" => "Lapas Kelas IIA Tanjung Raja", "cabang" => "Ogan Ilir"],
                ["provinsi" => "Sumatera Selatan", "nama" => "Lapas Kelas IIA Lubuk Linggau", "cabang" => "Lubuk Linggau"],
                ["provinsi" => "Sumatera Selatan", "nama" => "Lapas Kelas IIA Lahat", "cabang" => "Lahat"],
                ["provinsi" => "Sumatera Selatan", "nama" => "Lapas Kelas IIB Muara Enim", "cabang" => "Muara Enim"],
                ["provinsi" => "Sumatera Selatan", "nama" => "Lapas Kelas IIB Sekayu", "cabang" => "Musi Banyuasin"],
                ["provinsi" => "Sumatera Selatan", "nama" => "Lapas Kelas IIB Empat Lawang", "cabang" => "Tebing Tinggi"],
                ["provinsi" => "Sumatera Selatan", "nama" => "Lapas Kelas III Muaradua", "cabang" => "OKU Selatan"],
                ["provinsi" => "Sumatera Selatan", "nama" => "Lapas Narkotika Kelas IIA Muara Beliti", "cabang" => "Musi Rawas"],
                ["provinsi" => "Sumatera Selatan", "nama" => "Lapas Perempuan Kelas IIA Palembang", "cabang" => "Palembang"],
                ["provinsi" => "Sumatera Selatan", "nama" => "LPKA Kelas I Palembang", "cabang" => "Pakjo"],
                ["provinsi" => "Sumatera Selatan", "nama" => "Rutan Kelas I Palembang", "cabang" => "Pakjo"],
                ["provinsi" => "Sumatera Selatan", "nama" => "Rutan Kelas IIB Baturaja", "cabang" => "Ogan Komering Ulu"],
                ["provinsi" => "Sumatera Selatan", "nama" => "Rutan Kelas IIB Prabumulih", "cabang" => "Prabumulih"],
                ["provinsi" => "Sumatera Selatan", "nama" => "Rutan Kelas IIB Pagar Alam", "cabang" => "Pagar Alam"],
                ["provinsi" => "Sumatera Selatan", "nama" => "Rutan Kelas IIB Kayu Agung", "cabang" => "Ogan Komering Ilir"],
                ["provinsi" => "Sumatera Selatan", "nama" => "Lapas Narkotika Kelas IIB Banyuasin", "cabang" => "Banyuasin"],
                ["provinsi" => "Sumatera Selatan", "nama" => "Rutan Kelas IIB Martapura", "cabang" => "OKU Timur"],
                ["provinsi" => "Kepulauan Bangka Belitung", "nama" => "Lapas Kelas IIA Pangkal Pinang", "cabang" => "Pangkal Pinang"],
                ["provinsi" => "Kepulauan Bangka Belitung", "nama" => "Lapas Narkotika Kelas IIA Pangkal Pinang", "cabang" => "Pangkal Pinang"],
                ["provinsi" => "Kepulauan Bangka Belitung", "nama" => "Lapas Kelas IIB Sungailiat", "cabang" => "Bangka"],
                ["provinsi" => "Kepulauan Bangka Belitung", "nama" => "Lapas Kelas IIB Tanjung Pandan", "cabang" => "Belitung"],
                ["provinsi" => "Kepulauan Bangka Belitung", "nama" => "Lapas Kelas IIB Mentok", "cabang" => "Bangka Barat"],
                ["provinsi" => "Kepulauan Bangka Belitung", "nama" => "Lapas Perempuan Kelas III Pangkal Pinang", "cabang" => "Pangkal Pinang"],
                ["provinsi" => "Bengkulu", "nama" => "Lapas Kelas IIA Bengkulu", "cabang" => "Bengkulu"],
                ["provinsi" => "Bengkulu", "nama" => "Lapas Kelas IIB Argamakmur", "cabang" => "Bengkulu Utara"],
                ["provinsi" => "Bengkulu", "nama" => "Lapas Kelas IIB Curup", "cabang" => "Rejang Lebong"],
                ["provinsi" => "Bengkulu", "nama" => "Lapas Perempuan Kelas IIB Bengkulu", "cabang" => "Bengkulu"],
                ["provinsi" => "Bengkulu", "nama" => "LPKA Kelas II Bengkulu", "cabang" => "Bengkulu"],
                ["provinsi" => "Bengkulu", "nama" => "Rutan Kelas IIB Bengkulu", "cabang" => "Malabero"],
                ["provinsi" => "Bengkulu", "nama" => "Rutan Kelas IIB Manna", "cabang" => "Bengkulu Selatan"],
                ["provinsi" => "Lampung", "nama" => "Lapas Kelas I Bandar Lampung", "cabang" => "Rajabasa"],
                ["provinsi" => "Lampung", "nama" => "Lapas Kelas IIA Kalianda", "cabang" => "Lampung Selatan"],
                ["provinsi" => "Lampung", "nama" => "Lapas Kelas IIA Metro", "cabang" => "Metro"],
                ["provinsi" => "Lampung", "nama" => "Lapas Kelas IIB Kotabumi", "cabang" => "Lampung Utara"],
                ["provinsi" => "Lampung", "nama" => "Lapas Kelas IIB Way Kanan", "cabang" => "Way Kanan"],
                ["provinsi" => "Lampung", "nama" => "Lapas Kelas IIB Kota Agung", "cabang" => "Tanggamus"],
                ["provinsi" => "Lampung", "nama" => "Lapas Kelas IIB Gunung Sugih", "cabang" => "Lampung Tengah"],
                ["provinsi" => "Lampung", "nama" => "Lapas Kelas III Pringsewu", "cabang" => "Pringsewu"],
                ["provinsi" => "Lampung", "nama" => "Lapas Narkotika Kelas IIA Bandar Lampung", "cabang" => "Way Huwi"],
                ["provinsi" => "Lampung", "nama" => "Lapas Perempuan Kelas IIA Bandar Lampung", "cabang" => "Way Huwi"],
                ["provinsi" => "Lampung", "nama" => "LPKA Kelas II Bandar Lampung", "cabang" => "Lampung Selatan"],
                ["provinsi" => "Lampung", "nama" => "Rutan Kelas I Bandar Lampung", "cabang" => "Way Huwi"],
                ["provinsi" => "Lampung", "nama" => "Rutan Kelas IIB Kotabumi", "cabang" => "Lampung Utara"],
                ["provinsi" => "Lampung", "nama" => "Rutan Kelas IIB Menggala", "cabang" => "Tulang Bawang"],
                ["provinsi" => "Lampung", "nama" => "Rutan Kelas IIB Krui", "cabang" => "Pesisir Barat"],
                ["provinsi" => "Lampung", "nama" => "Rutan Kelas IIB Sukadana", "cabang" => "Lampung Timur"],
                ["provinsi" => "Lampung", "nama" => "Rutan Kelas IIB Labuhan Dalam", "cabang" => "Bandar Lampung"],
                ["provinsi" => "Lampung", "nama" => "Lapas Kelas IIB Gunung Sugih", "cabang" => "Lampung Tengah"],
                ["provinsi" => "DKI Jakarta", "nama" => "Lapas Kelas I Cipinang", "cabang" => "Jakarta Timur"],
                ["provinsi" => "DKI Jakarta", "nama" => "Lapas Narkotika Kelas IIA Jakarta", "cabang" => "Cipinang"],
                ["provinsi" => "DKI Jakarta", "nama" => "Lapas Perempuan Kelas IIA Jakarta", "cabang" => "Pondok Bambu"],
                ["provinsi" => "DKI Jakarta", "nama" => "LPKA Kelas II Jakarta", "cabang" => "Salemba"],
                ["provinsi" => "DKI Jakarta", "nama" => "Rutan Kelas I Jakarta Pusat", "cabang" => "Salemba"],
                ["provinsi" => "DKI Jakarta", "nama" => "Rutan Kelas I Jakarta Timur", "cabang" => "Cipinang"],
                ["provinsi" => "DKI Jakarta", "nama" => "Rutan Kelas I Jakarta Selatan", "cabang" => "Pondok Bambu"],
                ["provinsi" => "DKI Jakarta", "nama" => "Cabang Rutan KPK", "cabang" => "Gedung Merah Putih"],
                ["provinsi" => "DKI Jakarta", "nama" => "Cabang Rutan Kejaksaan Agung", "cabang" => "Salemba"],
                ["provinsi" => "DKI Jakarta", "nama" => "Cabang Rutan Mabes Polri", "cabang" => "Jakarta Selatan"],
                ["provinsi" => "DKI Jakarta", "nama" => "Lapas Kelas IIA Salemba", "cabang" => "Salemba"],
                ["provinsi" => "Jawa Barat", "nama" => "Lapas Kelas I Sukamiskin", "cabang" => "Bandung"],
                ["provinsi" => "Jawa Barat", "nama" => "Lapas Kelas I Cirebon", "cabang" => "Kesambi"],
                ["provinsi" => "Jawa Barat", "nama" => "Lapas Kelas IIA Cibinong", "cabang" => "Bogor"],
                ["provinsi" => "Jawa Barat", "nama" => "Lapas Kelas IIA Bekasi", "cabang" => "Bulak Kapal"],
                ["provinsi" => "Jawa Barat", "nama" => "Lapas Kelas IIA Karawang", "cabang" => "Karawang"],
                ["provinsi" => "Jawa Barat", "nama" => "Lapas Kelas IIA Bogor", "cabang" => "Paledang"],
                ["provinsi" => "Jawa Barat", "nama" => "Lapas Kelas IIA Kuningan", "cabang" => "Kuningan"],
                ["provinsi" => "Jawa Barat", "nama" => "Lapas Kelas IIA Subang", "cabang" => "Subang"],
                ["provinsi" => "Jawa Barat", "nama" => "Lapas Kelas IIB Purwakarta", "cabang" => "Purwakarta"],
                ["provinsi" => "Jawa Barat", "nama" => "Lapas Kelas IIB Indramayu", "cabang" => "Indramayu"],
                ["provinsi" => "Jawa Barat", "nama" => "Lapas Kelas IIB Majalengka", "cabang" => "Majalengka"],
                ["provinsi" => "Jawa Barat", "nama" => "Lapas Kelas IIB Cianjur", "cabang" => "Cianjur"],
                ["provinsi" => "Jawa Barat", "nama" => "Lapas Kelas IIB Warungkiara", "cabang" => "Sukabumi"],
                ["provinsi" => "Jawa Barat", "nama" => "Lapas Kelas IIB Banjar", "cabang" => "Banjar"],
                ["provinsi" => "Jawa Barat", "nama" => "Lapas Kelas IIB Cikarang", "cabang" => "Bekasi"],
                ["provinsi" => "Jawa Barat", "nama" => "Lapas Narkotika Kelas IIA Bandung", "cabang" => "Jelekong"],
                ["provinsi" => "Jawa Barat", "nama" => "Lapas Narkotika Kelas IIA Cirebon", "cabang" => "Gintung"],
                ["provinsi" => "Jawa Barat", "nama" => "Lapas Perempuan Kelas IIA Bandung", "cabang" => "Sukamaju"],
                ["provinsi" => "Jawa Barat", "nama" => "LPKA Kelas II Bandung", "cabang" => "Sukamaju"],
                ["provinsi" => "Jawa Barat", "nama" => "Rutan Kelas I Bandung", "cabang" => "Kebonwaru"],
                ["provinsi" => "Jawa Barat", "nama" => "Rutan Kelas I Depok", "cabang" => "Cilodong"],
                ["provinsi" => "Jawa Barat", "nama" => "Rutan Kelas IIB Garut", "cabang" => "Garut"],
                ["provinsi" => "Jawa Barat", "nama" => "Rutan Kelas IIB Sumedang", "cabang" => "Sumedang"],
                ["provinsi" => "Jawa Barat", "nama" => "Rutan Kelas IIB Sukabumi", "cabang" => "Sukabumi"],
                ["provinsi" => "Jawa Barat", "nama" => "Rutan Kelas IIB Ciamis", "cabang" => "Ciamis"],
                ["provinsi" => "Jawa Barat", "nama" => "Rutan Kelas IIB Tasikmalaya", "cabang" => "Tasikmalaya"],
                ["provinsi" => "Jawa Barat", "nama" => "Cabang Rutan Mabes Polri", "cabang" => "Kelapa Dua"],
                ["provinsi" => "Jawa Barat", "nama" => "Rutan Kelas IIB Gunung Sindur", "cabang" => "Bogor"],
                ["provinsi" => "Jawa Barat", "nama" => "Lapas Khusus Kelas IIA Gunung Sindur", "cabang" => "Bogor"],
                ["provinsi" => "Jawa Barat", "nama" => "Rutan Kelas I Cirebon", "cabang" => "Cirebon"],
                ["provinsi" => "Jawa Barat", "nama" => "Lapas Narkotika Kelas IIB Cirebon", "cabang" => "Cirebon"],
                ["provinsi" => "Jawa Barat", "nama" => "Lapas Kelas IIB Sentul", "cabang" => "Bogor"],
                ["provinsi" => "Jawa Barat", "nama" => "Lapas Kelas IIB Sukabumi", "cabang" => "Sukabumi"],
                ["provinsi" => "Jawa Barat", "nama" => "Lapas Kelas IIB Singaparna", "cabang" => "Tasikmalaya"],
                ["provinsi" => "Jawa Barat", "nama" => "Lapas Terbuka Kelas IIB Cinere", "cabang" => "Depok"],
                ["provinsi" => "Banten", "nama" => "Lapas Kelas I Tangerang", "cabang" => "Tangerang"],
                ["provinsi" => "Banten", "nama" => "Lapas Pemuda Kelas IIA Tangerang", "cabang" => "Tangerang"],
                ["provinsi" => "Banten", "nama" => "Lapas Kelas IIA Cilegon", "cabang" => "Cilegon"],
                ["provinsi" => "Banten", "nama" => "Lapas Kelas IIA Serang", "cabang" => "Serang"],
                ["provinsi" => "Banten", "nama" => "Lapas Perempuan Kelas IIA Tangerang", "cabang" => "Tangerang"],
                ["provinsi" => "Banten", "nama" => "LPKA Kelas I Tangerang", "cabang" => "Tangerang"],
                ["provinsi" => "Banten", "nama" => "Rutan Kelas I Tangerang", "cabang" => "Jambe"],
                ["provinsi" => "Banten", "nama" => "Rutan Kelas IIB Serang", "cabang" => "Serang"],
                ["provinsi" => "Banten", "nama" => "Rutan Kelas IIB Pandeglang", "cabang" => "Pandeglang"],
                ["provinsi" => "Banten", "nama" => "Rutan Kelas IIB Rangkasbitung", "cabang" => "Lebak"],
                ["provinsi" => "Banten", "nama" => "Lapas Kelas III Ciangir", "cabang" => "Tangerang"],
                ["provinsi" => "Jawa Tengah", "nama" => "Lapas Kelas I Batu", "cabang" => "Nusakambangan"],
                ["provinsi" => "Jawa Tengah", "nama" => "Lapas Kelas IIA Permisan", "cabang" => "Nusakambangan"],
                ["provinsi" => "Jawa Tengah", "nama" => "Lapas Kelas IIA Karanganyar", "cabang" => "Nusakambangan"],
                ["provinsi" => "Jawa Tengah", "nama" => "Lapas Kelas IIA Besi", "cabang" => "Nusakambangan"],
                ["provinsi" => "Jawa Tengah", "nama" => "Lapas Kelas IIA Kembang Kuning", "cabang" => "Nusakambangan"],
                ["provinsi" => "Jawa Tengah", "nama" => "Lapas Kelas IIA Pasir Putih", "cabang" => "Nusakambangan"],
                ["provinsi" => "Jawa Tengah", "nama" => "Lapas Narkotika Kelas IIA Nusakambangan", "cabang" => "Nusakambangan"],
                ["provinsi" => "Jawa Tengah", "nama" => "Lapas Kelas I Kedungpane", "cabang" => "Semarang"],
                ["provinsi" => "Jawa Tengah", "nama" => "Lapas Kelas IIA Purwokerto", "cabang" => "Banyumas"],
                ["provinsi" => "Jawa Tengah", "nama" => "Lapas Kelas IIA Magelang", "cabang" => "Magelang"],
                ["provinsi" => "Jawa Tengah", "nama" => "Lapas Kelas IIA Sragen", "cabang" => "Sragen"],
                ["provinsi" => "Jawa Tengah", "nama" => "Lapas Kelas IIA Pekalongan", "cabang" => "Pekalongan"],
                ["provinsi" => "Jawa Tengah", "nama" => "Lapas Kelas IIA Kendal", "cabang" => "Kendal"],
                ["provinsi" => "Jawa Tengah", "nama" => "Lapas Kelas IIA Tegal", "cabang" => "Tegal"],
                ["provinsi" => "Jawa Tengah", "nama" => "Lapas Kelas IIB Klaten", "cabang" => "Klaten"],
                ["provinsi" => "Jawa Tengah", "nama" => "Lapas Kelas IIB Slawi", "cabang" => "Tegal"],
                ["provinsi" => "Jawa Tengah", "nama" => "Lapas Kelas IIB Brebes", "cabang" => "Brebes"],
                ["provinsi" => "Jawa Tengah", "nama" => "Lapas Kelas IIB Pati", "cabang" => "Pati"],
                ["provinsi" => "Jawa Tengah", "nama" => "Lapas Kelas IIB Cilacap", "cabang" => "Cilacap"],
                ["provinsi" => "Jawa Tengah", "nama" => "Lapas Kelas IIB Purworejo", "cabang" => "Purworejo"],
                ["provinsi" => "Jawa Tengah", "nama" => "Lapas Terbuka Kelas IIB Kendal", "cabang" => "Kendal"],
                ["provinsi" => "Jawa Tengah", "nama" => "Lapas Perempuan Kelas IIA Semarang", "cabang" => "Bulu"],
                ["provinsi" => "Jawa Tengah", "nama" => "LPKA Kelas I Semarang", "cabang" => "Kutoarjo"],
                ["provinsi" => "Jawa Tengah", "nama" => "Rutan Kelas I Surakarta", "cabang" => "Solo"],
                ["provinsi" => "Jawa Tengah", "nama" => "Rutan Kelas I Semarang", "cabang" => "Kedungpane"],
                ["provinsi" => "Jawa Tengah", "nama" => "Rutan Kelas IIB Salatiga", "cabang" => "Salatiga"],
                ["provinsi" => "Jawa Tengah", "nama" => "Rutan Kelas IIB Wonosobo", "cabang" => "Wonosobo"],
                ["provinsi" => "Jawa Tengah", "nama" => "Rutan Kelas IIB Temanggung", "cabang" => "Temanggung"],
                ["provinsi" => "Jawa Tengah", "nama" => "Rutan Kelas IIB Kudus", "cabang" => "Kudus"],
                ["provinsi" => "Jawa Tengah", "nama" => "Rutan Kelas IIB Boyolali", "cabang" => "Boyolali"],
                ["provinsi" => "Jawa Tengah", "nama" => "Rutan Kelas IIB Kebumen", "cabang" => "Kebumen"],
                ["provinsi" => "Jawa Tengah", "nama" => "Rutan Kelas IIB Banjarnegara", "cabang" => "Banjarnegara"],
                ["provinsi" => "Jawa Tengah", "nama" => "Rutan Kelas IIB Purbalingga", "cabang" => "Purbalingga"],
                ["provinsi" => "Jawa Tengah", "nama" => "Rutan Kelas IIB Pemalang", "cabang" => "Pemalang"],
                ["provinsi" => "Jawa Tengah", "nama" => "Rutan Kelas IIB Blora", "cabang" => "Blora"],
                ["provinsi" => "Jawa Tengah", "nama" => "Rutan Kelas IIB Jepara", "cabang" => "Jepara"],
                ["provinsi" => "Jawa Tengah", "nama" => "Rutan Kelas IIB Batang", "cabang" => "Batang"],
                ["provinsi" => "Jawa Tengah", "nama" => "Rutan Kelas IIB Rembang", "cabang" => "Rembang"],
                ["provinsi" => "Jawa Tengah", "nama" => "Rutan Kelas IIB Sukoharjo", "cabang" => "Sukoharjo"],
                ["provinsi" => "Jawa Tengah", "nama" => "Rutan Kelas IIB Banyumas", "cabang" => "Banyumas"],
                ["provinsi" => "Jawa Tengah", "nama" => "Rutan Kelas IIB Demak", "cabang" => "Demak"],
                ["provinsi" => "Jawa Tengah", "nama" => "Rutan Kelas IIB Grobogan", "cabang" => "Purwodadi"],
                ["provinsi" => "Jawa Tengah", "nama" => "Rutan Kelas IIB Karanganyar", "cabang" => "Karanganyar"],
                ["provinsi" => "Jawa Tengah", "nama" => "Rutan Kelas IIB Pekalongan", "cabang" => "Lodoyong"],
                ["provinsi" => "Jawa Tengah", "nama" => "Lapas Kelas IIB Wonogiri", "cabang" => "Wonogiri"],
                ["provinsi" => "Jawa Tengah", "nama" => "Lapas Kelas III Ngaseman", "cabang" => "Nusakambangan"],
                ["provinsi" => "Jawa Tengah", "nama" => "Lapas Kelas III Gladakan", "cabang" => "Nusakambangan"],
                ["provinsi" => "DI Yogyakarta", "nama" => "Lapas Kelas IIA Yogyakarta", "cabang" => "Wirogunan"],
                ["provinsi" => "DI Yogyakarta", "nama" => "Lapas Narkotika Kelas IIA Yogyakarta", "cabang" => "Pakem"],
                ["provinsi" => "DI Yogyakarta", "nama" => "Lapas Perempuan Kelas IIB Yogyakarta", "cabang" => "Wonosari"],
                ["provinsi" => "DI Yogyakarta", "nama" => "LPKA Kelas II Yogyakarta", "cabang" => "Wonosari"],
                ["provinsi" => "DI Yogyakarta", "nama" => "Rutan Kelas IIA Yogyakarta", "cabang" => "Yogyakarta"],
                ["provinsi" => "DI Yogyakarta", "nama" => "Rutan Kelas IIB Bantul", "cabang" => "Pajangan"],
                ["provinsi" => "DI Yogyakarta", "nama" => "Rutan Kelas IIB Wates", "cabang" => "Kulon Progo"],
                ["provinsi" => "DI Yogyakarta", "nama" => "Rutan Kelas IIB Wonosari", "cabang" => "Gunung Kidul"],
                ["provinsi" => "Jawa Timur", "nama" => "Lapas Kelas I Lowokwaru", "cabang" => "Malang"],
                ["provinsi" => "Jawa Timur", "nama" => "Lapas Kelas I Porong", "cabang" => "Sidoarjo"],
                ["provinsi" => "Jawa Timur", "nama" => "Lapas Kelas I Madiun", "cabang" => "Madiun"],
                ["provinsi" => "Jawa Timur", "nama" => "Lapas Kelas IIA Jember", "cabang" => "Jember"],
                ["provinsi" => "Jawa Timur", "nama" => "Lapas Kelas IIA Kediri", "cabang" => "Kediri"],
                ["provinsi" => "Jawa Timur", "nama" => "Lapas Kelas IIA Bojonegoro", "cabang" => "Bojonegoro"],
                ["provinsi" => "Jawa Timur", "nama" => "Lapas Kelas IIA Banyuwangi", "cabang" => "Banyuwangi"],
                ["provinsi" => "Jawa Timur", "nama" => "Lapas Kelas IIA Pamekasan", "cabang" => "Pamekasan"],
                ["provinsi" => "Jawa Timur", "nama" => "Lapas Kelas IIA Mojokerto", "cabang" => "Mojokerto"],
                ["provinsi" => "Jawa Timur", "nama" => "Lapas Kelas IIB Tulungagung", "cabang" => "Tulungagung"],
                ["provinsi" => "Jawa Timur", "nama" => "Lapas Kelas IIB Blitar", "cabang" => "Blitar"],
                ["provinsi" => "Jawa Timur", "nama" => "Lapas Kelas IIB Tuban", "cabang" => "Tuban"],
                ["provinsi" => "Jawa Timur", "nama" => "Lapas Kelas IIB Lamongan", "cabang" => "Lamongan"],
                ["provinsi" => "Jawa Timur", "nama" => "Lapas Kelas IIB Pasuruan", "cabang" => "Pasuruan"],
                ["provinsi" => "Jawa Timur", "nama" => "Lapas Kelas IIB Probolinggo", "cabang" => "Probolinggo"],
                ["provinsi" => "Jawa Timur", "nama" => "Lapas Kelas IIB Lumajang", "cabang" => "Lumajang"],
                ["provinsi" => "Jawa Timur", "nama" => "Lapas Kelas IIB Bondowoso", "cabang" => "Bondowoso"],
                ["provinsi" => "Jawa Timur", "nama" => "Lapas Kelas IIB Situbondo", "cabang" => "Situbondo"],
                ["provinsi" => "Jawa Timur", "nama" => "Lapas Kelas IIB Ngawi", "cabang" => "Ngawi"],
                ["provinsi" => "Jawa Timur", "nama" => "Lapas Kelas IIB Jombang", "cabang" => "Jombang"],
                ["provinsi" => "Jawa Timur", "nama" => "Lapas Kelas IIB Arjasa Situbondo", "cabang" => "Situbondo"],
                ["provinsi" => "Jawa Timur", "nama" => "Lapas Narkotika Kelas IIA Pamekasan", "cabang" => "Pamekasan"],
                ["provinsi" => "Jawa Timur", "nama" => "Lapas Narkotika Kelas IIA Madiun", "cabang" => "Madiun"],
                ["provinsi" => "Jawa Timur", "nama" => "Lapas Perempuan Kelas IIA Malang", "cabang" => "Sukun"],
                ["provinsi" => "Jawa Timur", "nama" => "LPKA Kelas I Blitar", "cabang" => "Blitar"],
                ["provinsi" => "Jawa Timur", "nama" => "Rutan Kelas I Surabaya", "cabang" => "Medaeng"],
                ["provinsi" => "Jawa Timur", "nama" => "Rutan Kelas IIB Gresik", "cabang" => "Gresik"],
                ["provinsi" => "Jawa Timur", "nama" => "Rutan Kelas IIB Sidoarjo", "cabang" => "Sidoarjo"],
                ["provinsi" => "Jawa Timur", "nama" => "Rutan Kelas IIB Bangkalan", "cabang" => "Madura"],
                ["provinsi" => "Jawa Timur", "nama" => "Rutan Kelas IIB Sampang", "cabang" => "Madura"],
                ["provinsi" => "Jawa Timur", "nama" => "Rutan Kelas IIB Sumenep", "cabang" => "Madura"],
                ["provinsi" => "Jawa Timur", "nama" => "Rutan Kelas IIB Situbondo", "cabang" => "Situbondo"],
                ["provinsi" => "Jawa Timur", "nama" => "Rutan Kelas IIB Trenggalek", "cabang" => "Trenggalek"],
                ["provinsi" => "Jawa Timur", "nama" => "Rutan Kelas IIB Kraksaan", "cabang" => "Probolinggo"],
                ["provinsi" => "Jawa Timur", "nama" => "Rutan Kelas IIB Nganjuk", "cabang" => "Nganjuk"],
                ["provinsi" => "Jawa Timur", "nama" => "Rutan Kelas IIB Pacitan", "cabang" => "Pacitan"],
                ["provinsi" => "Jawa Timur", "nama" => "Rutan Kelas IIB Ponorogo", "cabang" => "Ponorogo"],
                ["provinsi" => "Jawa Timur", "nama" => "Rutan Kelas IIB Magetan", "cabang" => "Magetan"],
                ["provinsi" => "Jawa Timur", "nama" => "Rutan Kelas IIB Madiun", "cabang" => "Madiun"],
                ["provinsi" => "Jawa Timur", "nama" => "Rutan Kelas IIB Kediri", "cabang" => "Kediri"],
                ["provinsi" => "Jawa Timur", "nama" => "Lapas Kelas I Surabaya", "cabang" => "Porong"],
                ["provinsi" => "Jawa Timur", "nama" => "Lapas Perempuan Kelas IIA Surabaya", "cabang" => "Porong"],
                ["provinsi" => "Jawa Timur", "nama" => "Lapas Narkotika Kelas IIB Madiun", "cabang" => "Madiun"],
                ["provinsi" => "Bali", "nama" => "Lapas Kelas IIA Kerobokan", "cabang" => "Badung"],
                ["provinsi" => "Bali", "nama" => "Lapas Narkotika Kelas IIA Bangli", "cabang" => "Bangli"],
                ["provinsi" => "Bali", "nama" => "Lapas Perempuan Kelas IIA Kerobokan", "cabang" => "Badung"],
                ["provinsi" => "Bali", "nama" => "Lapas Kelas IIB Singaraja", "cabang" => "Buleleng"],
                ["provinsi" => "Bali", "nama" => "Lapas Kelas IIB Tabanan", "cabang" => "Tabanan"],
                ["provinsi" => "Bali", "nama" => "LPKA Kelas II Karangasem", "cabang" => "Karangasem"],
                ["provinsi" => "Bali", "nama" => "Rutan Kelas IIB Gianyar", "cabang" => "Gianyar"],
                ["provinsi" => "Bali", "nama" => "Rutan Kelas IIB Klungkung", "cabang" => "Klungkung"],
                ["provinsi" => "Bali", "nama" => "Rutan Kelas IIB Bangli", "cabang" => "Bangli"],
                ["provinsi" => "Bali", "nama" => "Rutan Kelas IIB Negara", "cabang" => "Jembrana"],
                ["provinsi" => "Bali", "nama" => "Rutan Kelas IIB Karangasem", "cabang" => "Karangasem"],
                ["provinsi" => "Nusa Tenggara Barat", "nama" => "Lapas Kelas IIA Mataram", "cabang" => "Kuripan"],
                ["provinsi" => "Nusa Tenggara Barat", "nama" => "Lapas Kelas IIB Sumbawa Besar", "cabang" => "Sumbawa"],
                ["provinsi" => "Nusa Tenggara Barat", "nama" => "Lapas Kelas IIB Dompu", "cabang" => "Dompu"],
                ["provinsi" => "Nusa Tenggara Barat", "nama" => "Lapas Perempuan Kelas III Mataram", "cabang" => "Mataram"],
                ["provinsi" => "Nusa Tenggara Barat", "nama" => "LPKA Kelas II Mataram", "cabang" => "Mataram"],
                ["provinsi" => "Nusa Tenggara Barat", "nama" => "Rutan Kelas IIB Praya", "cabang" => "Lombok Tengah"],
                ["provinsi" => "Nusa Tenggara Barat", "nama" => "Rutan Kelas IIB Selong", "cabang" => "Lombok Timur"],
                ["provinsi" => "Nusa Tenggara Barat", "nama" => "Rutan Kelas IIB Bima", "cabang" => "Kota Bima"],
                ["provinsi" => "Nusa Tenggara Barat", "nama" => "Lapas Terbuka Kelas IIB Mataram", "cabang" => "Lombok Barat"],
                ["provinsi" => "Nusa Tenggara Timur", "nama" => "Lapas Kelas IIA Kupang", "cabang" => "Kupang"],
                ["provinsi" => "Nusa Tenggara Timur", "nama" => "Lapas Kelas IIB Atambua", "cabang" => "Belu"],
                ["provinsi" => "Nusa Tenggara Timur", "nama" => "Lapas Kelas IIB Waingapu", "cabang" => "Sumba Timur"],
                ["provinsi" => "Nusa Tenggara Timur", "nama" => "Lapas Kelas IIB Waikabubak", "cabang" => "Sumba Barat"],
                ["provinsi" => "Nusa Tenggara Timur", "nama" => "Lapas Kelas IIB Kalabahi", "cabang" => "Alor"],
                ["provinsi" => "Nusa Tenggara Timur", "nama" => "Lapas Perempuan Kelas III Kupang", "cabang" => "Kupang"],
                ["provinsi" => "Nusa Tenggara Timur", "nama" => "LPKA Kelas I Kupang", "cabang" => "Kupang"],
                ["provinsi" => "Nusa Tenggara Timur", "nama" => "Rutan Kelas IIB Larantuka", "cabang" => "Flores Timur"],
                ["provinsi" => "Nusa Tenggara Timur", "nama" => "Rutan Kelas IIB Bajawa", "cabang" => "Ngada"],
                ["provinsi" => "Nusa Tenggara Timur", "nama" => "Rutan Kelas IIB Maumere", "cabang" => "Sikka"],
                ["provinsi" => "Nusa Tenggara Timur", "nama" => "Rutan Kelas IIB Ende", "cabang" => "Ende"],
                ["provinsi" => "Nusa Tenggara Timur", "nama" => "Rutan Kelas IIB Ruteng", "cabang" => "Manggarai"],
                ["provinsi" => "Nusa Tenggara Timur", "nama" => "Rutan Kelas IIB Soe", "cabang" => "Timor Tengah Selatan"],
                ["provinsi" => "Nusa Tenggara Timur", "nama" => "Rutan Kelas IIB Kefamenanu", "cabang" => "Timor Tengah Utara"],
                ["provinsi" => "Nusa Tenggara Timur", "nama" => "Rutan Kelas IIB Kupang", "cabang" => "Kupang"],
                ["provinsi" => "Nusa Tenggara Timur", "nama" => "Lapas Kelas IIB Lembata", "cabang" => "Lembata"],
                ["provinsi" => "Nusa Tenggara Timur", "nama" => "Lapas Kelas IIB Labuan Bajo", "cabang" => "Manggarai Barat"],
                ["provinsi" => "Nusa Tenggara Timur", "nama" => "Lapas Kelas III Baa", "cabang" => "Rote Ndao"],
                ["provinsi" => "Nusa Tenggara Timur", "nama" => "Lapas Kelas III Betun", "cabang" => "Malaka"],
                ["provinsi" => "Nusa Tenggara Timur", "nama" => "Lapas Terbuka Kelas IIB Kupang", "cabang" => "Kupang"],
                ["provinsi" => "Kalimantan Barat", "nama" => "Lapas Kelas IIA Pontianak", "cabang" => "Sungai Raya"],
                ["provinsi" => "Kalimantan Barat", "nama" => "Lapas Kelas IIB Singkawang", "cabang" => "Singkawang"],
                ["provinsi" => "Kalimantan Barat", "nama" => "Lapas Kelas IIB Ketapang", "cabang" => "Ketapang"],
                ["provinsi" => "Kalimantan Barat", "nama" => "Lapas Kelas IIB Sintang", "cabang" => "Sintang"],
                ["provinsi" => "Kalimantan Barat", "nama" => "Lapas Perempuan Kelas IIA Pontianak", "cabang" => "Pontianak"],
                ["provinsi" => "Kalimantan Barat", "nama" => "LPKA Kelas II Sungai Raya", "cabang" => "Kubu Raya"],
                ["provinsi" => "Kalimantan Barat", "nama" => "Rutan Kelas IIA Pontianak", "cabang" => "Pontianak"],
                ["provinsi" => "Kalimantan Barat", "nama" => "Rutan Kelas IIB Mempawah", "cabang" => "Mempawah"],
                ["provinsi" => "Kalimantan Barat", "nama" => "Rutan Kelas IIB Sanggau", "cabang" => "Sanggau"],
                ["provinsi" => "Kalimantan Barat", "nama" => "Rutan Kelas IIB Sambas", "cabang" => "Sambas"],
                ["provinsi" => "Kalimantan Barat", "nama" => "Rutan Kelas IIB Putussibau", "cabang" => "Kapuas Hulu"],
                ["provinsi" => "Kalimantan Barat", "nama" => "Rutan Kelas IIB Landak", "cabang" => "Landak"],
                ["provinsi" => "Kalimantan Barat", "nama" => "Rutan Kelas IIB Bengkayang", "cabang" => "Bengkayang"],
                ["provinsi" => "Kalimantan Barat", "nama" => "Lapas Kelas III Sukadana", "cabang" => "Kayong Utara"],
                ["provinsi" => "Kalimantan Tengah", "nama" => "Lapas Kelas IIA Palangkaraya", "cabang" => "Palangkaraya"],
                ["provinsi" => "Kalimantan Tengah", "nama" => "Lapas Kelas IIB Pangkalan Bun", "cabang" => "Kotawaringin Barat"],
                ["provinsi" => "Kalimantan Tengah", "nama" => "Lapas Kelas IIB Sampit", "cabang" => "Kotawaringin Timur"],
                ["provinsi" => "Kalimantan Tengah", "nama" => "Lapas Kelas IIB Muara Teweh", "cabang" => "Barito Utara"],
                ["provinsi" => "Kalimantan Tengah", "nama" => "Lapas Narkotika Kelas IIA Kasongan", "cabang" => "Katingan"],
                ["provinsi" => "Kalimantan Tengah", "nama" => "Lapas Perempuan Kelas IIA Palangkaraya", "cabang" => "Palangkaraya"],
                ["provinsi" => "Kalimantan Tengah", "nama" => "LPKA Kelas II Palangkaraya", "cabang" => "Palangkaraya"],
                ["provinsi" => "Kalimantan Tengah", "nama" => "Rutan Kelas IIA Palangkaraya", "cabang" => "Palangkaraya"],
                ["provinsi" => "Kalimantan Tengah", "nama" => "Rutan Kelas IIB Buntok", "cabang" => "Barito Selatan"],
                ["provinsi" => "Kalimantan Tengah", "nama" => "Rutan Kelas IIB Kapuas", "cabang" => "Kapuas"],
                ["provinsi" => "Kalimantan Tengah", "nama" => "Rutan Kelas IIB Tamiang Layang", "cabang" => "Barito Timur"],
                ["provinsi" => "Kalimantan Tengah", "nama" => "Rutan Kelas IIB Sukamara", "cabang" => "Sukamara"],
                ["provinsi" => "Kalimantan Tengah", "nama" => "Lapas Kelas III Sukamara", "cabang" => "Sukamara"],
                ["provinsi" => "Kalimantan Selatan", "nama" => "Lapas Kelas IIA Banjarmasin", "cabang" => "Teluk Dalam"],
                ["provinsi" => "Kalimantan Selatan", "nama" => "Lapas Kelas IIB Banjarbaru", "cabang" => "Banjarbaru"],
                ["provinsi" => "Kalimantan Selatan", "nama" => "Lapas Kelas IIB Amuntai", "cabang" => "Hulu Sungai Utara"],
                ["provinsi" => "Kalimantan Selatan", "nama" => "Lapas Kelas IIB Kotabaru", "cabang" => "Kotabaru"],
                ["provinsi" => "Kalimantan Selatan", "nama" => "Lapas Kelas IIB Tanjung", "cabang" => "Tabalong"],
                ["provinsi" => "Kalimantan Selatan", "nama" => "Lapas Narkotika Kelas IIA Karang Intan", "cabang" => "Banjar"],
                ["provinsi" => "Kalimantan Selatan", "nama" => "Lapas Perempuan Kelas IIA Martapura", "cabang" => "Banjar"],
                ["provinsi" => "Kalimantan Selatan", "nama" => "LPKA Kelas I Martapura", "cabang" => "Banjar"],
                ["provinsi" => "Kalimantan Selatan", "nama" => "Rutan Kelas IIB Kandangan", "cabang" => "Hulu Sungai Selatan"],
                ["provinsi" => "Kalimantan Selatan", "nama" => "Rutan Kelas IIB Barabai", "cabang" => "Hulu Sungai Tengah"],
                ["provinsi" => "Kalimantan Selatan", "nama" => "Rutan Kelas IIB Marabahan", "cabang" => "Barito Kuala"],
                ["provinsi" => "Kalimantan Selatan", "nama" => "Rutan Kelas IIB Pelaihari", "cabang" => "Tanah Laut"],
                ["provinsi" => "Kalimantan Selatan", "nama" => "Rutan Kelas IIB Banjarmasin", "cabang" => "Banjarmasin"],
                ["provinsi" => "Kalimantan Selatan", "nama" => "Rutan Kelas IIB Rantau", "cabang" => "Tapin"],
                ["provinsi" => "Kalimantan Selatan", "nama" => "Lapas Kelas III Batulicin", "cabang" => "Tanah Bumbu"],
                ["provinsi" => "Kalimantan Timur", "nama" => "Lapas Kelas IIA Samarinda", "cabang" => "Samarinda"],
                ["provinsi" => "Kalimantan Timur", "nama" => "Lapas Kelas IIA Balikpapan", "cabang" => "Balikpapan"],
                ["provinsi" => "Kalimantan Timur", "nama" => "Lapas Kelas IIB Tenggarong", "cabang" => "Kutai Kartanegara"],
                ["provinsi" => "Kalimantan Timur", "nama" => "Lapas Kelas IIB Bontang", "cabang" => "Bontang"],
                ["provinsi" => "Kalimantan Timur", "nama" => "Lapas Kelas III Bontang", "cabang" => "Bontang"],
                ["provinsi" => "Kalimantan Timur", "nama" => "Lapas Narkotika Kelas IIA Samarinda", "cabang" => "Bayur"],
                ["provinsi" => "Kalimantan Timur", "nama" => "Lapas Perempuan Kelas IIA Tenggarong", "cabang" => "Kutai Kartanegara"],
                ["provinsi" => "Kalimantan Timur", "nama" => "LPKA Kelas II Tenggarong", "cabang" => "Kutai Kartanegara"],
                ["provinsi" => "Kalimantan Timur", "nama" => "Rutan Kelas IIA Samarinda", "cabang" => "Samarinda"],
                ["provinsi" => "Kalimantan Timur", "nama" => "Rutan Kelas IIB Balikpapan", "cabang" => "Balikpapan"],
                ["provinsi" => "Kalimantan Timur", "nama" => "Rutan Kelas IIB Tanah Grogot", "cabang" => "Paser"],
                ["provinsi" => "Kalimantan Timur", "nama" => "Rutan Kelas IIB Tanjung Redeb", "cabang" => "Berau"],
                ["provinsi" => "Kalimantan Timur", "nama" => "Lapas Narkotika Kelas IIB Samarinda", "cabang" => "Samarinda"],
                ["provinsi" => "Kalimantan Timur", "nama" => "Lapas Terbuka Kelas IIB Samarinda", "cabang" => "Samarinda"],
                ["provinsi" => "Kalimantan Utara", "nama" => "Lapas Kelas IIB Nunukan", "cabang" => "Nunukan"],
                ["provinsi" => "Kalimantan Utara", "nama" => "Lapas Kelas IIB Tarakan", "cabang" => "Tarakan"],
                ["provinsi" => "Sulawesi Utara", "nama" => "Lapas Kelas IIA Manado", "cabang" => "Tuminting"],
                ["provinsi" => "Sulawesi Utara", "nama" => "Lapas Kelas IIB Bitung", "cabang" => "Bitung"],
                ["provinsi" => "Sulawesi Utara", "nama" => "Lapas Kelas IIB Tondano", "cabang" => "Minahasa"],
                ["provinsi" => "Sulawesi Utara", "nama" => "Lapas Kelas IIB Tahuna", "cabang" => "Kepulauan Sangihe"],
                ["provinsi" => "Sulawesi Utara", "nama" => "Lapas Kelas IIB Ulu Siau", "cabang" => "Sitaro"],
                ["provinsi" => "Sulawesi Utara", "nama" => "Lapas Perempuan Kelas IIB Manado", "cabang" => "Tomohon"],
                ["provinsi" => "Sulawesi Utara", "nama" => "LPKA Kelas II Tomohon", "cabang" => "Tomohon"],
                ["provinsi" => "Sulawesi Utara", "nama" => "Rutan Kelas IIA Manado", "cabang" => "Malendeng"],
                ["provinsi" => "Sulawesi Utara", "nama" => "Rutan Kelas IIB Kotamobagu", "cabang" => "Kotamobagu"],
                ["provinsi" => "Sulawesi Utara", "nama" => "Rutan Kelas IIB Amurang", "cabang" => "Minahasa Selatan"],
                ["provinsi" => "Sulawesi Utara", "nama" => "Rutan Kelas IIB Lirik", "cabang" => "Talaud"],
                ["provinsi" => "Sulawesi Utara", "nama" => "Lapas Kelas III Tagulandang", "cabang" => "Sitaro"],
                ["provinsi" => "Sulawesi Utara", "nama" => "Lapas Kelas III Enemawira", "cabang" => "Sangihe"],
                ["provinsi" => "Sulawesi Utara", "nama" => "Lapas Kelas III Amurang", "cabang" => "Minahasa Selatan"],
                ["provinsi" => "Sulawesi Tengah", "nama" => "Lapas Kelas IIA Palu", "cabang" => "Palu"],
                ["provinsi" => "Sulawesi Tengah", "nama" => "Lapas Kelas IIB Luwuk", "cabang" => "Banggai"],
                ["provinsi" => "Sulawesi Tengah", "nama" => "Lapas Kelas IIB Ampana", "cabang" => "Tojo Una-Una"],
                ["provinsi" => "Sulawesi Tengah", "nama" => "Lapas Kelas IIB Tolitoli", "cabang" => "Tolitoli"],
                ["provinsi" => "Sulawesi Tengah", "nama" => "Lapas Perempuan Kelas III Palu", "cabang" => "Sigi"],
                ["provinsi" => "Sulawesi Tengah", "nama" => "LPKA Kelas II Palu", "cabang" => "Palu"],
                ["provinsi" => "Sulawesi Tengah", "nama" => "Rutan Kelas IIA Palu", "cabang" => "Palu"],
                ["provinsi" => "Sulawesi Tengah", "nama" => "Rutan Kelas IIB Donggala", "cabang" => "Donggala"],
                ["provinsi" => "Sulawesi Tengah", "nama" => "Rutan Kelas IIB Poso", "cabang" => "Poso"],
                ["provinsi" => "Sulawesi Tengah", "nama" => "Rutan Kelas IIB Parigi", "cabang" => "Parigi Moutong"],
                ["provinsi" => "Sulawesi Tengah", "nama" => "Lapas Kelas III Leok", "cabang" => "Buol"],
                ["provinsi" => "Sulawesi Tengah", "nama" => "Lapas Kelas IIB Kolonodale", "cabang" => "Morowali"],
                ["provinsi" => "Sulawesi Tengah", "nama" => "Lapas Kelas III Kolonodale", "cabang" => "Morowali"],
                ["provinsi" => "Sulawesi Selatan", "nama" => "Lapas Kelas I Makassar", "cabang" => "Bolangi"],
                ["provinsi" => "Sulawesi Selatan", "nama" => "Lapas Kelas IIA Parepare", "cabang" => "Parepare"],
                ["provinsi" => "Sulawesi Selatan", "nama" => "Lapas Kelas IIA Watampone", "cabang" => "Bone"],
                ["provinsi" => "Sulawesi Selatan", "nama" => "Lapas Kelas IIA Palopo", "cabang" => "Palopo"],
                ["provinsi" => "Sulawesi Selatan", "nama" => "Lapas Kelas IIA Bulukumba", "cabang" => "Bulukumba"],
                ["provinsi" => "Sulawesi Selatan", "nama" => "Lapas Kelas IIB Takalar", "cabang" => "Takalar"],
                ["provinsi" => "Sulawesi Selatan", "nama" => "Lapas Kelas IIB Maros", "cabang" => "Maros"],
                ["provinsi" => "Sulawesi Selatan", "nama" => "Lapas Narkotika Kelas IIA Sungguminasa", "cabang" => "Gowa"],
                ["provinsi" => "Sulawesi Selatan", "nama" => "Lapas Perempuan Kelas IIA Sungguminasa", "cabang" => "Gowa"],
                ["provinsi" => "Sulawesi Selatan", "nama" => "LPKA Kelas II Maros", "cabang" => "Maros"],
                ["provinsi" => "Sulawesi Selatan", "nama" => "Rutan Kelas I Makassar", "cabang" => "Gunung Sari"],
                ["provinsi" => "Sulawesi Selatan", "nama" => "Rutan Kelas IIB Pinrang", "cabang" => "Pinrang"],
                ["provinsi" => "Sulawesi Selatan", "nama" => "Rutan Kelas IIB Jeneponto", "cabang" => "Jeneponto"],
                ["provinsi" => "Sulawesi Selatan", "nama" => "Rutan Kelas IIB Bantaeng", "cabang" => "Bantaeng"],
                ["provinsi" => "Sulawesi Selatan", "nama" => "Rutan Kelas IIB Sidrap", "cabang" => "Sidenreng Rappang"],
                ["provinsi" => "Sulawesi Selatan", "nama" => "Rutan Kelas IIB Sinjai", "cabang" => "Sinjai"],
                ["provinsi" => "Sulawesi Selatan", "nama" => "Rutan Kelas IIB Selayar", "cabang" => "Kepulauan Selayar"],
                ["provinsi" => "Sulawesi Selatan", "nama" => "Rutan Kelas IIB Barru", "cabang" => "Barru"],
                ["provinsi" => "Sulawesi Selatan", "nama" => "Rutan Kelas IIB Makale", "cabang" => "Tana Toraja"],
                ["provinsi" => "Sulawesi Selatan", "nama" => "Rutan Kelas IIB Masamba", "cabang" => "Luwu Utara"],
                ["provinsi" => "Sulawesi Selatan", "nama" => "Rutan Kelas IIB Pangkajene", "cabang" => "Pangkep"],
                ["provinsi" => "Sulawesi Selatan", "nama" => "Rutan Kelas IIB Soppeng", "cabang" => "Watansoppeng"],
                ["provinsi" => "Sulawesi Selatan", "nama" => "Rutan Kelas IIB Malino", "cabang" => "Gowa"],
                ["provinsi" => "Sulawesi Selatan", "nama" => "Rutan Kelas IIB Sengkang", "cabang" => "Wajo"],
                ["provinsi" => "Sulawesi Selatan", "nama" => "Rutan Kelas IIB Enrekang", "cabang" => "Enrekang"],
                ["provinsi" => "Sulawesi Selatan", "nama" => "Rutan Kelas IIB Rappang", "cabang" => "Sidrap"],
                ["provinsi" => "Sulawesi Tenggara", "nama" => "Lapas Kelas IIA Kendari", "cabang" => "Kendari"],
                ["provinsi" => "Sulawesi Tenggara", "nama" => "Lapas Kelas IIA Bau-Bau", "cabang" => "Bau-Bau"],
                ["provinsi" => "Sulawesi Tenggara", "nama" => "Lapas Narkotika Kelas IIA Kendari", "cabang" => "Kendari"],
                ["provinsi" => "Sulawesi Tenggara", "nama" => "Lapas Perempuan Kelas III Kendari", "cabang" => "Kendari"],
                ["provinsi" => "Sulawesi Tenggara", "nama" => "LPKA Kelas II Kendari", "cabang" => "Kendari"],
                ["provinsi" => "Sulawesi Tenggara", "nama" => "Rutan Kelas IIA Kendari", "cabang" => "Kendari"],
                ["provinsi" => "Sulawesi Tenggara", "nama" => "Rutan Kelas IIB Raha", "cabang" => "Muna"],
                ["provinsi" => "Sulawesi Tenggara", "nama" => "Rutan Kelas IIB Unaaha", "cabang" => "Konawa"],
                ["provinsi" => "Sulawesi Tenggara", "nama" => "Rutan Kelas IIB Kolaka", "cabang" => "Kolaka"],
                ["provinsi" => "Sulawesi Tenggara", "nama" => "Lapas Terbuka Kelas IIB Kendari", "cabang" => "Kendari"],
                ["provinsi" => "Gorontalo", "nama" => "Lapas Kelas IIA Gorontalo", "cabang" => "Gorontalo"],
                ["provinsi" => "Gorontalo", "nama" => "Lapas Kelas IIB Pohuwato", "cabang" => "Pohuwato"],
                ["provinsi" => "Gorontalo", "nama" => "Lapas Kelas IIB Boalemo", "cabang" => "Boalemo"],
                ["provinsi" => "Gorontalo", "nama" => "LPKA Kelas II Gorontalo", "cabang" => "Gorontalo"],
                ["provinsi" => "Gorontalo", "nama" => "Lapas Perempuan Kelas III Gorontalo", "cabang" => "Gorontalo"],
                ["provinsi" => "Sulawesi Barat", "nama" => "Lapas Kelas IIB Polewali", "cabang" => "Polewali Mandar"],
                ["provinsi" => "Sulawesi Barat", "nama" => "Lapas Perempuan Kelas III Mamuju", "cabang" => "Mamuju"],
                ["provinsi" => "Sulawesi Barat", "nama" => "Rutan Kelas IIB Mamuju", "cabang" => "Mamuju"],
                ["provinsi" => "Sulawesi Barat", "nama" => "Rutan Kelas IIB Majene", "cabang" => "Majene"],
                ["provinsi" => "Sulawesi Barat", "nama" => "Rutan Kelas IIB Pasangkayu", "cabang" => "Pasangkayu"],
                ["provinsi" => "Maluku", "nama" => "Lapas Kelas IIA Ambon", "cabang" => "Ambon"],
                ["provinsi" => "Maluku", "nama" => "Lapas Kelas IIB Saparua", "cabang" => "Maluku Tengah"],
                ["provinsi" => "Maluku", "nama" => "Lapas Kelas IIB Piru", "cabang" => "Seram Bagian Barat"],
                ["provinsi" => "Maluku", "nama" => "Lapas Kelas IIB Namlea", "cabang" => "Buru"],
                ["provinsi" => "Maluku", "nama" => "Lapas Perempuan Kelas III Ambon", "cabang" => "Ambon"],
                ["provinsi" => "Maluku", "nama" => "LPKA Kelas II Ambon", "cabang" => "Ambon"],
                ["provinsi" => "Maluku", "nama" => "Rutan Kelas IIA Ambon", "cabang" => "Tantui"],
                ["provinsi" => "Maluku", "nama" => "Rutan Kelas IIB Masohi", "cabang" => "Maluku Tengah"],
                ["provinsi" => "Maluku", "nama" => "Rutan Kelas IIB Banda Naira", "cabang" => "Maluku Tengah"],
                ["provinsi" => "Maluku", "nama" => "Lapas Kelas III Saumlaki", "cabang" => "Tanimbar"],
                ["provinsi" => "Maluku", "nama" => "Lapas Kelas III Dobo", "cabang" => "Kepulauan Aru"],
                ["provinsi" => "Maluku", "nama" => "Lapas Kelas III Wonreli", "cabang" => "Maluku Barat Daya"],
                ["provinsi" => "Maluku", "nama" => "Lapas Terbuka Kelas IIB Ambon", "cabang" => "Ambon"],
                ["provinsi" => "Maluku", "nama" => "Lapas Kelas III Piru", "cabang" => "Seram Bagian Barat"],
                ["provinsi" => "Maluku Utara", "nama" => "Lapas Kelas IIA Ternate", "cabang" => "Ternate"],
                ["provinsi" => "Maluku Utara", "nama" => "Lapas Kelas IIB Tobelo", "cabang" => "Halmahera Utara"],
                ["provinsi" => "Maluku Utara", "nama" => "Lapas Kelas IIB Sanana", "cabang" => "Kepulauan Sula"],
                ["provinsi" => "Maluku Utara", "nama" => "Lapas Kelas IIB Jailolo", "cabang" => "Halmahera Barat"],
                ["provinsi" => "Maluku Utara", "nama" => "Lapas Perempuan Kelas III Ternate", "cabang" => "Ternate"],
                ["provinsi" => "Maluku Utara", "nama" => "LPKA Kelas II Ternate", "cabang" => "Ternate"],
                ["provinsi" => "Maluku Utara", "nama" => "Rutan Kelas IIB Soasiu", "cabang" => "Tidore"],
                ["provinsi" => "Maluku Utara", "nama" => "Rutan Kelas IIB Weda", "cabang" => "Halmahera Tengah"],
                ["provinsi" => "Maluku Utara", "nama" => "Lapas Kelas III Labuha", "cabang" => "Halmahera Selatan"],
                ["provinsi" => "Maluku Utara", "nama" => "Lapas Kelas III Maba", "cabang" => "Halmahera Timur"],
                ["provinsi" => "Papua", "nama" => "Lapas Kelas IIA Abepura", "cabang" => "Jayapura"],
                ["provinsi" => "Papua", "nama" => "Lapas Kelas IIB Merauke", "cabang" => "Merauke"],
                ["provinsi" => "Papua", "nama" => "Lapas Kelas IIB Wamena", "cabang" => "Jayawijaya"],
                ["provinsi" => "Papua", "nama" => "Lapas Kelas IIB Biak", "cabang" => "Biak Numfor"],
                ["provinsi" => "Papua", "nama" => "Lapas Kelas IIB Serui", "cabang" => "Kepulauan Yapen"],
                ["provinsi" => "Papua", "nama" => "Lapas Narkotika Kelas IIA Jayapura", "cabang" => "Doyo Baru"],
                ["provinsi" => "Papua", "nama" => "Lapas Perempuan Kelas III Jayapura", "cabang" => "Keerom"],
                ["provinsi" => "Papua", "nama" => "LPKA Kelas II Jayapura", "cabang" => "Jayapura"],
                ["provinsi" => "Papua", "nama" => "Rutan Kelas IIB Jayapura", "cabang" => "Abepura"],
                ["provinsi" => "Papua", "nama" => "Rutan Kelas IIB Tanah Merah", "cabang" => "Boven Digoel"],
                ["provinsi" => "Papua", "nama" => "Lapas Kelas III Waropen", "cabang" => "Waropen"],
                ["provinsi" => "Papua", "nama" => "Lapas Kelas III Tanah Merah", "cabang" => "Boven Digoel"],
                ["provinsi" => "Papua", "nama" => "Lapas Kelas III Arso", "cabang" => "Keerom"],
                ["provinsi" => "Papua", "nama" => "Lapas Terbuka Kelas IIB Jayapura", "cabang" => "Jayapura"],
                ["provinsi" => "Papua", "nama" => "Lapas Kelas IIB Nabire", "cabang" => "Nabire"],
                ["provinsi" => "Papua", "nama" => "Lapas Kelas IIB Timika", "cabang" => "Mimika"],
                ["provinsi" => "Papua", "nama" => "Rutan Kelas IIB Enarotali", "cabang" => "Paniai"],
                ["provinsi" => "Papua Barat", "nama" => "Lapas Kelas IIB Manokwari", "cabang" => "Manokwari"],
                ["provinsi" => "Papua Barat", "nama" => "Lapas Kelas IIB Fakfak", "cabang" => "Fakfak"],
                ["provinsi" => "Papua Barat", "nama" => "Lapas Kelas III Kaimana", "cabang" => "Kaimana"],
                ["provinsi" => "Papua Barat", "nama" => "Lapas Perempuan Kelas III Manokwari", "cabang" => "Manokwari"],
                ["provinsi" => "Papua Barat", "nama" => "LPKA Kelas II Manokwari", "cabang" => "Manokwari"],
                ["provinsi" => "Papua Barat Daya", "nama" => "Lapas Kelas IIB Sorong", "cabang" => "Sorong"],
                ["provinsi" => "Papua Pegunungan", "nama" => "Lapas Kelas IIB Wamena", "cabang" => "Jayawijaya"]
        ];

        foreach ($prisons as $data) {
            Prison::updateOrCreate(
                [
                    'province' => $data['provinsi'],
                    'name' => $data['nama'],
                    'branch' => $data['cabang'],
                ],
                [
                    'puskarda_id' => null,
                    'spptti_id' => null,
                    'is_active' => true,
                ]
            );
        }
    }
}