<?php

namespace Database\Seeders\Personals;

use Illuminate\Database\Seeder;

use App\Models\Meta\Personals\Job;

class JobsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $jobs = [
            ["id" => "1", "name" => "Tidak Diketahui"],
            ["id" => "2", "name" => "PNS"],
            ["id" => "3", "name" => "Mahasiswa"],
            ["id" => "4", "name" => "Karyawan Swasta"],
            ["id" => "5", "name" => "Polri"],
            ["id" => "6", "name" => "Buruh"],
            ["id" => "7", "name" => "Pelajar"],
            ["id" => "8", "name" => "Wiraswasta"],
            ["id" => "9", "name" => "Tuna Karya"],
            ["id" => "10", "name" => "TNI AU"],
            ["id" => "11", "name" => "Juru Bahasa"],
            ["id" => "12", "name" => "Nelayan"],
            ["id" => "13", "name" => "Tani"],
            ["id" => "14", "name" => "Pengacara"],
            ["id" => "15", "name" => "Dosen"],
            ["id" => "16", "name" => "Guru"],
            ["id" => "17", "name" => "Supir"],
            ["id" => "18", "name" => "Pendeta"],
            ["id" => "19", "name" => "Wartawan"],
            ["id" => "20", "name" => "Honorer"],
            ["id" => "21", "name" => "ABK"],
            ["id" => "22", "name" => "Hakim"],
            ["id" => "23", "name" => "Jaksa"],
            ["id" => "24", "name" => "Advokat"],
            ["id" => "25", "name" => "Dukun Beranak"],
            ["id" => "26", "name" => "Akuntan"],
            ["id" => "27", "name" => "Apoteker"],
            ["id" => "28", "name" => "Atlet / Olahragawan"],
            ["id" => "29", "name" => "Pelaut"],
            ["id" => "30", "name" => "Bidan"],
            ["id" => "31", "name" => "Dokter"],
            ["id" => "32", "name" => "Mucikari"],
            ["id" => "33", "name" => "Notaris"],
            ["id" => "34", "name" => "Paramedis"],
            ["id" => "35", "name" => "Paranormal"],
            ["id" => "36", "name" => "Pilot"],
            ["id" => "37", "name" => "Seniman"],
            ["id" => "38", "name" => "Pramugari"],
            ["id" => "39", "name" => "Ibu Rumah Tangga"],
            ["id" => "40", "name" => "Pramugara"],
            ["id" => "41", "name" => "Pemulung"],
            ["id" => "42", "name" => "Tukang Bangunan"],
            ["id" => "43", "name" => "Tukang Kayu"],
            ["id" => "44", "name" => "Direktur Perusahaan"],
            ["id" => "45", "name" => "Satpam / Security Perusahaan"],
            ["id" => "46", "name" => "Cleaning Service"],
            ["id" => "47", "name" => "Pedagang"],
            ["id" => "48", "name" => "Tukang Ojek"],
            ["id" => "49", "name" => "Pensiunan Pns"],
            ["id" => "50", "name" => "Debt Collector / Penagih Utang"],
            ["id" => "51", "name" => "Purnawirawan TNI AD"],
            ["id" => "52", "name" => "Pegawai Bumd"],
            ["id" => "53", "name" => "Pegawai Bumn"],
            ["id" => "54", "name" => "Kontraktor"],
            ["id" => "55", "name" => "Anggota DPR"],
            ["id" => "56", "name" => "Gubernur"],
            ["id" => "57", "name" => "Wakil Gubernur"],
            ["id" => "58", "name" => "Mekanik"],
            ["id" => "59", "name" => "Purnawirawan TNI AL"],
            ["id" => "60", "name" => "Purnawirawan TNI AU"],
            ["id" => "61", "name" => "Reporter TV"],
            ["id" => "62", "name" => "Tukang Kebun"],
            ["id" => "63", "name" => "PNS Polri"],
            ["id" => "64", "name" => "Tukang Ledeng / Pipa"],
            ["id" => "65", "name" => "Purnawirawan Polri"],
            ["id" => "66", "name" => "WTS"],
            ["id" => "67", "name" => "TKI"],
            ["id" => "68", "name" => "TNI AL"],
            ["id" => "69", "name" => "TNI AD"],
            ["id" => "70", "name" => "Bupati"],
            ["id" => "71", "name" => "Wakil Bupati"],
            ["id" => "72", "name" => "Anggota DPRD Provinsi"],
            ["id" => "73", "name" => "Anggota DPRD Kab / Kota"],
            ["id" => "74", "name" => "Perangkat Desa"],
            ["id" => "75", "name" => "Kepala Desa"],
            ["id" => "76", "name" => "Kernet Kendaraan Umum"],
            ["id" => "77", "name" => "Porter Pelabuhan"],
            ["id" => "78", "name" => "Porter Bandara"],
            ["id" => "79", "name" => "Tukang Parkir"],
            ["id" => "80", "name" => "Komisaris Perusahaan"],
            ["id" => "81", "name" => "Legal Manager"],
            ["id" => "82", "name" => "Tukang Pangkas Rambut"],
            ["id" => "83", "name" => "Asisten Rumah Tangga"],
            ["id" => "84", "name" => "Pegawai Bea dan Cukai"],
            ["id" => "85", "name" => "Montir Kendaraan"],
            ["id" => "86", "name" => "Tukang Pijit"],
            ["id" => "87", "name" => "Ulama / Ustad"],
            ["id" => "88", "name" => "Teknisi Elektronik"],
            ["id" => "89", "name" => "Penambang"],
            ["id" => "90", "name" => "Buruh Pabrik"],
            ["id" => "91", "name" => "Penjaga Sekolah"],
            ["id" => "92", "name" => "Artis"],
            ["id" => "93", "name" => "Pegawai Lapas / Rutan"],
            ["id" => "94", "name" => "Tidak Bekerja"],
            ["id" => "95", "name" => "Lain-Lain"],
            ["id" => "96", "name" => "Nahkoda"],
            ["id" => "97", "name" => "Masinis"],
            ["id" => "98", "name" => "Menteri"],
            ["id" => "99", "name" => "Walikota"],
            ["id" => "100", "name" => "Paralegal"],
            ["id" => "101", "name" => "Penjahit"],
            ["id" => "102", "name" => "Konsultan Hukum"],
            ["id" => "103", "name" => "Wakil Walikota"],
            ["id" => "104", "name" => "Karyawan Bank"],
            ["id" => "105", "name" => "Kurator"],
            ["id" => "106", "name" => "Komisioner KPU"],
            ["id" => "107", "name" => "Teknisi"],
            ["id" => "108", "name" => "Pegawai OJK"],
            ["id" => "109", "name" => "Pastor"],
            ["id" => "110", "name" => "Peternak"],
            ["id" => "111", "name" => "industri"],
            ["id" => "112", "name" => "konstruksi"],
            ["id" => "113", "name" => "transportasi"],
            ["id" => "114", "name" => "Buruh Harian Lepas"],
            ["id" => "115", "name" => "Buruh tani / perkebunan"],
            ["id" => "116", "name" => "Buruh nelayan / perikanan"],
            ["id" => "117", "name" => "Buruh peternakan"],
            ["id" => "118", "name" => "Tukang listrik"],
            ["id" => "119", "name" => "Tukang batu"],
            ["id" => "120", "name" => "Tukang sol sepatu"],
            ["id" => "121", "name" => "Tukang las/pandai besi"],
            ["id" => "122", "name" => "Penata rias"],
            ["id" => "123", "name" => "Penata busana"],
            ["id" => "124", "name" => "Penata Rambut"],
            ["id" => "125", "name" => "Tukang gigi"],
            ["id" => "126", "name" => "tabib"],
            ["id" => "127", "name" => "Paraji"],
            ["id" => "128", "name" => "Perancang busana"],
            ["id" => "129", "name" => "Penterjemah"],
            ["id" => "130", "name" => "Imam masjid"],
            ["id" => "131", "name" => "Juru masak"],
            ["id" => "132", "name" => "Promotor acara"],
            ["id" => "133", "name" => "Anggota DPD"],
            ["id" => "134", "name" => "Anggota BPK"],
            ["id" => "135", "name" => "Presiden"],
            ["id" => "136", "name" => "Wakil Presiden"],
            ["id" => "137", "name" => "Anggota Mahkamah Konstitusi"],
            ["id" => "138", "name" => "Duta Besar"],
            ["id" => "139", "name" => "Arsitek"],
            ["id" => "140", "name" => "Konsultan"],
            ["id" => "141", "name" => "Perawat"],
            ["id" => "142", "name" => "Psikiater/psikolog"],
            ["id" => "143", "name" => "Penyiar televisi"],
            ["id" => "144", "name" => "Penyiar radio"],
            ["id" => "145", "name" => "Peneliti"],
            ["id" => "146", "name" => "Pialang"],
            ["id" => "147", "name" => "Perdagangan"],
            ["id" => "148", "name" => "Biarawati"],
            ["id" => "149", "name" => "Pekerjaan selain N"],
        ];

        foreach($jobs as $job){
            Job::create([
                'id' => $job['id'],
                'name' => $job['name']
            ]);
        }
        
    }
}
